### ISSUE TITLE
Add example of how a radial gradients degenerates to a strip/cone under transforms

### ISSUE THREAD

**Issue by drott** [googlefonts/colr-gradients-spec#106]
See #96

**Comment by PeterConstable** [comment]
@drott We describe this case in 5.7.11.1.2.3. Do you still think an example of this should be added?

**Comment by drott** [comment]
Closing, the NOTE in that section describes this accurately.

> NOTE: A scale transformation can flatten shapes to resemble lines. If a radial gradient is nested in the child sub-graph of a transformation that flattens the circles so that they are nearly lines, the centers could still be separated by some distance. In that case, the radial gradient would appear as a strip or a cone filled with a linear gradient.
