### ISSUE TITLE
clarify "a radial gradient may appear"

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#109]
"May" implies something is permitted and optional. So, in this note,

>_**Note:** When a radial gradient is nested below a transformation which flattens the circles so that they resemble lines, a radial gradient may appear as a strip or a cone filled with a linear gradient._

the wording, seems to be saying that implementations are permitted to do this, but are also permitted to do something else. Is that intended?

Also, in ISO-speak, "may" is not permitted in a note. (OT hasn't had that rule, so some exceptions to the rule may have crept into OFF from OT.)

If the intent of the statement is, "The algorithm (when correctly implemented) will produce a linear gradient", we should word the note that way.

If the intent is that the algorithm doesn't determine the result in this case and that a linear gradient is a permitted result, then it would be better not to put into a note. Also, since the behaviour is optional, fonts that do this could behave differently in different implementations, and so we might way to add a statement along the lines that fonts should not do this.

The options hinge on whether this is determined by the algorithm or not. My reading of the algorithm suggests to me that it doesn't determine a result in that case.

**Comment by svgeesus** [comment]
Ideally, the algorithm would say what the result is.

Failing that, there should probably be authoring advice that extreme transformations which turn a 2D shape into a close-to-1D shape are likely to result in non-interoperable gradients due to precision and rounding issues, and that authors should therefore avoid them.

Unless this is an attempt to create strips or cones, but that seems unlikely? Although, as there are no clip paths, maybe cones are an intended result?

**Comment by PeterCon** [comment]
This also pertains to #22: I suspect the thinking reflected in the text is a holdover from an earlier version in which the PaintRadial included a transform applied to the circles, affecting their shape but not the placement of the centers. Now with the transform separate, if the circles are flattened to a line, then both circles and their centers will be colinear.

If the flattening is _not quite_ to zero, then the circles aren't _quite_ flat, though perhaps flat enough that they end up being drawn as lines (perhaps even less than a pixel wide). Yet @drott makes the point that, if the centers were very far apart to begin with, there may still be significant distance between the centers even though the circles resemble lines. 

But I think for that scenario the algorithm is clear enough. It's when the distance between the centers also approaches zero that the algorithm isn't quite clear about expected results.

**Comment by PeterConstable** [comment]
Wording has since been improved. Closing.
