### ISSUE TITLE
Base of offsets needs to be specified

### ISSUE THREAD

**Issue by behdad** [googlefonts/colr-gradients-spec#11]
Currently it's not.  In GSUB/GPOS most offsets are from the beginning of whatever parent struct was referred to by an offset.  I'll add followup comment with details of the problem.  Filing for now so we don't forget.

**Comment by anthrotype** [comment]
> offsets are from the beginning of whatever parent struct was referred to by an offset

yeah, I was also wondering about that when I implemented the current draft spec in fonttools. I ended up doing exactly that.

**Comment by PeterConstable** [comment]
Need to be clear about "whatever parent struct": always from a _table_, never a _record_.

**Comment by behdad** [comment]
@PeterConstable Here's a truly new pattern proposal: offsets that are based at their own start address.  These will be self-sufficient.  What's your appetite for that?

**Comment by behdad** [comment]
> Need to be clear about "whatever parent struct": always from a _table_, never a _record_

Is this definition of _table_, as something always referred to by offset, versus non-table, documented in the spec?

Is everything else, other than basic types, called a _record_?

**Comment by PeterConstable** [comment]
Not as such, that I'm aware of. But it's part of the general conventions: 

* Things accessed by offset are either 
  * (sub)tables or,
  * arrays of records, where the count and offset are stored in the parent table header

* Things that are called tables are always referred by offset, where the offset is stored in the parent table header or in a record within an array in the parent table, and the offset is from the start of the parent table.

* Records are usually used in arrays. There may be cases in which a single struct occurring sequentially within a table is called a "record", but if so it's not often.
* Records never contain subtables / never have offsets to structs where the offset is from the start of the record.
* Records often contain offsets, but always an offset from the start of the parent table.

**Comment by behdad** [comment]
> * arrays of records, where the count and offset are stored in the parent table header
> *

This patently false.  I'm replying in https://github.com/googlefonts/colr-gradients-spec/issues/14 now.

**Comment by behdad** [comment]
And that offsets are always relative from the beginning of the current table unless specified otherwise.

**Comment by behdad** [comment]
> @PeterConstable Here's a truly new pattern proposal: offsets that are based at their own start address. These will be self-sufficient. What's your appetite for that?

Curious about your thoughts on this.  Note that it has been done like that back in `glyf` table.  But yeah we not talking about tables designed before 2000....

**Comment by PeterConstable** [comment]
>offsets that are based at their own start address
I'm not sure what that means.

>* Things accessed by offset are either
>   * (sub)tables or,
>   * arrays of records, where the count and offset are stored in the parent table header
>
>This patently false. I'm replying in #14 now.

As you point out, a struct referenced by offset that is [count, [records]] is considered a table. That's the first sub-bullet I listed. Examples of the second sub-bullet above would include the COLR baseGlyphRecords or layerRecords arrays, CPAL colorRecords array, gvar sharedTuples array...

**Comment by behdad** [comment]
> As you point out, a struct referenced by offset that is [count, [records]] is considered a table. That's the first sub-bullet I listed. Examples of the second sub-bullet above would include the COLR baseGlyphRecords or layerRecords arrays, CPAL colorRecords array, gvar sharedTuples array...

I have a problem with even specifying that second point.  Why is it different from anything else?  A table is bunch of structs and things.  Some tables are self-contained to parse, others need to access values outside values, which might be coming from parent table or grandparents, or elsewhere in the font.  I have been pushing towards self-contained tables as much as possible.

**Comment by PeterConstable** [comment]
I wasn't suggesting it be formalized in the spec. I was only describing conventions that I see have been used in the spec up to now.

There is a common pattern of  logical organization like

```python
fooTable = {
  'barTables': []
}
```
where what gets stored in the file is analogous to 

```python
fooTable = {
  'barRecords': [ 
      {'field': <val>, 'barOffset': <offset>},
      {'field': <val>, 'barOffset': <offset>},
      ...
}
```
Logically, the bar tables are sub-tables of foo. And you want the offsets to them to be from the start of foo. Having the barRecods array be an immediate member of foo is consistent with the logical arrangement and point in the hierarchy where you want to access things.

What I was reacting to in your proposal spec was having `Offset32<BaseGlyphV1Array>` with the array of records being a count-initial struct but not calling it out as a table. It suggested to me that the  offsets in the records are from the start of COLR. And that suggested there's a sub-struct of COLR with offsets for COLR subtables -- so the records are nested a layer deeper than the subtables they point to. That felt wrong, and not consistent with "self-contained tables as much as possible".

But when it became glyph that the intent is for offsets to be from the start of that sub-struct, then it all fell into place with existing patterns: that sub-struct is a sub-table, and the record offsets are pointing to sub-tables of that sub-table.

It does add a layer in the structural hierarchy that could be avoided. But it's consistent with existing patterns and maintains the "self-contained as much as possible" principle.

**Comment by PeterConstable** [comment]
>It does add a layer in the structural hierarchy that could be avoided. 

But the way to avoid it would have been to have a record array at an offset and the account for the array back in the parent table. So, that would be less in line with "self contained as much as possible". So, having the BaseGlyphV1List table as an additional layer is a good choice.

**Comment by behdad** [comment]
> > It does add a layer in the structural hierarchy that could be avoided.

The reason we don't do that is this:

It is an anti-pattern to have an array in a table unless at the very end. Because anything that comes after the array will be at a variable, not fixed, position in the table, that makes parsing harder.  There are cases that making an exception to this make sense. But in general that should be considered an anti-pattern and avoided.

Now, even if we embedded the BaseGlyphV1List at the end of the table, the next versions of the table would then exhibit the above anti-pattern.

**Comment by PeterConstable** [comment]
The base of offsets has since been made clear, and the proposed structures are consistent with existing OT spec patterns: a structure that has an array of subtable offsets is a "table" and the offsets are relative to the start of the table. The proposal is now consistent with that.

Closing.

**Comment by PeterConstable** [comment]
@behdad I think this can be closed.

**Comment by behdad** [comment]
> @behdad I think this can be closed.

Fine with me.

I'm still interested in and going to root for having self-based offsets for all new tables in OT moving forward.

**Comment by behdad** [comment]
> I'm still interested in and going to root for having self-based offsets for all new tables in OT moving forward.

That's very similar to `offset_ptr` in Boost: https://www.boost.org/doc/libs/1_35_0/doc/html/interprocess/offset_ptr.html

**Comment by rsheeter** [comment]
Closing per IM confirmation with Behdad we're happy for COLR, new offset type can be picked up elsewhere.
