### ISSUE TITLE
Use 32-bit glyphIDs?

### ISSUE THREAD

**Issue by Lorp** [googlefonts/colr-gradients-spec#114]
Would it be a good idea to pad all glyphID fields to 32 bits in COLRv1? My thinking is that it will be convenient if recently respecced tables can be used without modification in experimental and real forthcoming OpenType/CommonType formats that use 32-bit glyphIDs.

**Comment by anthrotype** [comment]
duplicate of https://github.com/googlefonts/colr-gradients-spec/issues/95, in turn duplicate of #8 ?

**Comment by Lorp** [comment]
Yikes! One day really is like every other. Apologies for the dupe of my own dupe.
