### ISSUE TITLE
Add informative reference to SVG Native

### ISSUE THREAD

**Issue by svgeesus** [googlefonts/colr-gradients-spec#117]
> It is our understanding that this brings the capabilities of COLR/CPAL to match those of SVG Native for vector graphics. 

That is a fairly weak assertion. It is also difficult to check for readers of the document. I suggest instead

This brings the capabilities of COLR/CPAL to match those of [SVG Native](https://svgwg.org/specs/svg-native/) for vector graphics, except for the inclusion of raster images and the use of clipping paths.

And add https://svgwg.org/specs/svg-native/ to the informative references

**Comment by anthrotype** [comment]
> clipping paths

Those could be achieved with nested PaintGlyphs. The path of the parent PaintGlyph "clips" the path of the child PaintGlyph.

**Comment by svgeesus** [comment]
Interesting, should be added as an example

**Comment by PeterConstable** [comment]
>>>    clipping paths
>>
>>Those could be achieved with nested PaintGlyphs. The path of the parent PaintGlyph "clips" the path of the child PaintGlyph.
>
>Interesting, should be added as an example

See clause 5.7.11.1.3 Filling shapes in [section A.2](https://github.com/googlefonts/colr-gradients-spec/blob/master/colr-gradients-spec.md#a2-changes-to-off-5711---color-table)

**Comment by PeterConstable** [comment]
While it might be useful for this temporary doc, but the OFF content isn't mentioning SVG Native. So, @svgeesus @rsheeter I think this could be closed.

**Comment by svgeesus** [comment]
Fair enough

**Comment by PeterConstable** [comment]
I've added the link to the svg-native doc in PR #194. Note that this is in the cover doc, not in the OFF Amd2 WD content.

**Comment by PeterConstable** [comment]
This has been addressed, so closing.
