### ISSUE TITLE
Clarify "An implementation may chose to implement this as clipping "

### ISSUE THREAD

**Issue by svgeesus** [googlefonts/colr-gradients-spec#118]
This seems to mix up two things

a) the fact that this can be used to clip a painted area
b) a non-normative implementation note about one common way to implement clipping functionality.

Since some people (me!) missed the fact that clipping was possible, on a first read, it would be good to move the mention of clipping out from the note and into the definition of the glyph paint.

**Comment by PeterConstable** [comment]
@svgeesus See if this is addressed in clause 5.7.11.1.3 Filling shapes in [section A.2](https://github.com/googlefonts/colr-gradients-spec/blob/master/colr-gradients-spec.md#a2-changes-to-off-5711---color-table)

**Comment by svgeesus** [comment]
Yes that seems much better!

**Comment by PeterConstable** [comment]
Closing as this has been clarified in the current OFF draft text.
