### ISSUE TITLE
add flag field to layer record?

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#13]
In #3 LP mentions the "white on black" issue. He notes a mechanism that's already defined in the current COLR spec:

"A palette entry index value of 0xFFFF is a special case indicating that the text foreground color (defined by a higher-level client) should be used and shall not be treated as actual index into CPAL ColorRecord array."

And so suggests that an additional special case be defined in COLR, 0xFFFE, to mean "punch a hole in all previous layers".

Another approach that could be considered would be to add a separate flags field in the layer record. The flags could be used to indicate different blending options with previous layers, including "punch all previous layers", or "punch previous layer". (When punching, the separate paletteIndex could indicate a fill for the punched area?)

**Note:** I haven't thought through in detail what potential benefits are, or what problem would remain if not provided. (E.g., wouldn't it work to just add another non-punch layer on top?) The original issue that brought this up had to do with winding interactions of **overlapping contours within a single glyph**, not any interaction between different glyphs. So, I'm just throwing this out for discussion.

**Comment by davelab6** [comment]
>  The original issue that brought this up had to do with winding interactions of overlapping contours within a single glyph

That will be common for color variable fonts, which I thihk is a high priority to support well

**Comment by rsheeter** [comment]
+1 to blend mode per layer unless @drott knows of a reason that's a terrible idea, seems like a really nice addition. Optimistically assuming it's fine then the question is what list of modes? Are any of the Cairo modes a problem for non-Cairo environments?

**Comment by drott** [comment]
From an initial inspection `SkBlendMode` ([code](https://source.chromium.org/chromium/chromium/src/+/master:third_party/skia/include/core/SkBlendMode.h;l=13?q=SkBlendMode)) supports the identical set compared to cairo operators.

**Comment by rsheeter** [comment]
Courtesy of @bungeman on #32, copying here because it seems very helpful toward deciding what initial set of blends to support:

> As far as blend modes, basically everyone supports the basic porter-duff blend modes (everything down to kLastCoeffMode in the [Skia blend modes](https://source.chromium.org/chromium/chromium/src/+/master:third_party/skia/include/core/SkBlendMode.h;l=13?q=SkBlendMode&ss=chromium%2Fchromium%2Fsrc)). I'd have to check but that list pretty much lines up with what SVG does. [D2D](https://docs.microsoft.com/en-us/windows/win32/api/d2d1_1/ne-d2d1_1-d2d1_composite_mode) seems to not support all of them for some reason and [CoreGraphics](https://developer.apple.com/documentation/coregraphics/cgblendmode?language=objc) seems to do all of them. May want to take the intersection of these. Note that the 'clear' blend mode satisfies the general desire for the 'punch a hole' operation.

**Comment by rsheeter** [comment]
#35 is my initial strawman for adding this.

**Comment by behdad** [comment]
Copying my comment from https://github.com/googlefonts/colr-gradients-spec/pull/35#issuecomment-687901031

Here's my counter-proposal for adding blending modes as well as alpha-channel gradients (aka masking):
```
struct PaintCompose
{
  uint16              format; // = 5
  Operator         op;
  Offset32<Paint> src;  
};
struct PaintMask
{
  uint16              format; // = 6
  Offset32<Paint> src;
  Offset32<Paint> mask;
};
```

**Comment by rsheeter** [comment]
That also works for me, replied on #35 in slightly more detail.

**Comment by behdad** [comment]
Should we close this and discuss in #35?

**Comment by rsheeter** [comment]
Agreed, at this point none of the options is adding a flag to layer so lets close.
