### ISSUE TITLE
v1 BaseGlyph / Layer records introduce a pattern for structures that is new to OT

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#14]
The draft introduces a pattern for structures that doesn't have existing precedent in OpenType. It's certainly implementable. But would it be preferable to stick with existing models already used?

I noticed this while trying to implement the draft in a old parsing implementation I have in VB: For an array of base glyph records each of which has an offset to a (different) array of layer records, I was going to end up creating a collection of collections. I had previously only ever done that for _an interpretation_ of structures (e.g. glyph IDs in a glyph class).

A different approach that would follow an existing precedent would be to have v1 BaseGlyph be a _table_ (not record) that includes an array of layer records, each of which has an offset to a Fill table. That would match the model currently used for ScriptList and FeatureList.

**Comment by anthrotype** [comment]
is this a duplicate of https://github.com/googlefonts/colr-gradients-spec/issues/12 ?

**Comment by PeterConstable** [comment]
Yes, but I provide more details here, so I'd suggest the other be closed.

**Comment by behdad** [comment]
You didn't even fully explain what you are objecting to.  Reading all various issues I assume what you mean is: the length of the array referred to by offset is stored before the array values, ie. at the destination of the offset.  Whereas you claim in OT it must be stored in the parent object.

> The draft introduces a pattern for structures that doesn't have existing precedent in OpenType.

There's so many things wrong with this statement.

Tables are a common pattern in OT.  They are referred to by offset.  Arrays are a common pattern in OT, they are mostly stored as length followed by items.  There are deviations from that, mostly when there are multiple arrays that need to be stored in the same table.

Now you are telling me that a table that consists of just an array is a deviation from the common patterns.  That's bizarre.  A table stores whatever it needs to store.  If it only needs to store an array, then we get a table that is just an array.  If we didn't call it a table in the proposal, sure, go ahead and rename it to a table.  I don't care about the wording, but the structure is solid and your objection doesn't make sense to me.

Here: I found a few cases of "table that solely consists of an array":

`MarkArray` table in GPOS:
https://docs.microsoft.com/en-us/typography/opentype/spec/gpos#markArrayTable

`AttachPoint` table in GDEF:
https://docs.microsoft.com/en-us/typography/opentype/spec/gdef#attachment-point-list-table

`LigGlyph` table in GDEF:
https://docs.microsoft.com/en-us/typography/opentype/spec/gdef#ligature-glyph-table

So your claim that "a pattern for structures that is new to OT" is false.

Now if you want to discuss whether storing things a different way is better, I'm open to discussing that.

Storing length just before elements means that in pretty much every programming language the array can be represented as one self-contained object.  Storing the length anywhere else means that any code dealing with the array needs more work to relate the array to where the length is stored.

**Comment by PeterConstable** [comment]
The key point is that the offsets in the records use the start of that table as the base. Your spec hadn't clarified and so my default assumption was that the offsets were from the start of COLR. That would be a departure.

If you follow the thread in #18 , you'll see that when I started parsing Noto-Handwriting-COLR_1 I discovered that what your preliminary implementation in fonttools had done was to treat the array like a subtable, analogous to mark array table, etc. And so this _is_ following existing precedents:

>OK, it looks like the base you have used for the LayerV1 arrays is the start of the the BGRV1 array -- that is, the location of the count for the BGRV1 array.
>
>To put that into the existing paradigms in the OT spec, that BGRV1 "array" would be a table.

And you'll see in my drafts [here](https://github.com/PeterConstable/OT_Drafts/tree/master/COLR_V1)\*, that that is what is reflected: this is what I called the **_BaseGlyphV1List_ table**. 

\* Rev2 matches what I found in that font. Rev3 incorporates a re-ordering of PaintFormat3 fields, so it doesn't match the font.

Nobody has commented on my drafts. If we are in agreement wrt BaseGlyphV1List as a subtable, then this issue is resolved and can be closed.

**Comment by behdad** [comment]
Yes I think we are in agreement.

I'm expecting that @rsheeter or @anthrotype will go through all the issues and resolve based on the consensus.

**Comment by anthrotype** [comment]
> If we are in agreement wrt BaseGlyphV1List as a subtable, then this issue is resolved

Agreed. For consistency, since we rename `BaseGlyphV1Array` to `BaseGlyphV1List`, I believe we should also rename `LayerV1Array` to `LayerV1List`. In @PeterConstable's draft rev3, this is currently called `LayersV1` (with a plural noun).

https://github.com/PeterConstable/OT_Drafts/blob/master/COLR_V1/COLRv1formats_rev3.md#layersv1-table

**Comment by PeterConstable** [comment]
>For consistency, since we rename BaseGlyphV1Array to BaseGlyphV1List, I believe we should also rename LayerV1Array to LayerV1List.

That idea had occurred to me independently. When I left off a couple of months ago, I wasn't completely happy with names in this part.

We don't need to include "V1" in new struct names just because these are added in COLR v1. For instance, we could use "BaseGlyphList" since that name isn't used for any existing struct, though in that particular case I think I would keep "BaseGlyphV1List" to clarify distinction between that and the structs used in v0. But I think "LayerV1List" could be shorted to "LayerList" since it's obvious that struct is only used in conjunction with BaseGlyphV1List.

**Comment by behdad** [comment]
+1 to not including "V1" in names.

**Comment by PeterConstable** [comment]
I've created a rev4 of my formats spec that incorporates a name change from LayersV1 to LayerList. Please add comments in [this PR](https://github.com/PeterConstable/OT_Drafts/pull/3/files) if there are other name changes worth considering.

**Comment by PeterConstable** [comment]
This is resolved in the draft of format descriptions for the OT spec I created [here](https://github.com/PeterConstable/OT_Drafts/blob/master/COLR_V1/COLRv1formats_rev4.md).

Closing.
