### ISSUE TITLE
Label figures individually, esp gradients

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#145]
In cases like 5.13 where we show 3 gradient images consider labelling per-image so the label can indicate exactly what is in the image (e.g. this one is pad/reflect, etc)

**Comment by PeterConstable** [comment]
@rsheeter For figure 5.12, do you suggest this be split into six figures?

**Comment by PeterConstable** [comment]
I'll do this after PRs for the various sub-clauses of the Graphic compositions clause are merged: this will affect number of many figures.

**Comment by PeterConstable** [comment]
Done: PRs #188, #189, #190
