### ISSUE TITLE
Clarify expected behaviour of radial gradient if circles are the same.

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#150]
If both circles have the same center and the same non-zero radius, then the algorithm would paint only a circle (without thickness, or minimum possible thickness) with the first extended color at positive infinity. "Color at infinity" isn't well defined. The areas within or outside the circles would not be painted.

SVG has a noticeably different behaviour, which resembles having circles of _very slightly different_ radii, with that difference approaching zero. 

* For pad mode, the interior and exterior are painted with solid colors of the first and last (or vice versa?) stops. 

* For repeat and reflect modes, the interior and exterior are painted with the same colour --- for the red/yellow/blue in our example images, it comes out a muddy yellow. This is where the different-radii-approaching-zero behaviour can be seen: if you make the circles with slightly different radii and zoom in, you'll see there is gradation; but zoomed out, the effect looks like a solid muddy yellow but with moirée patterns. If the difference in radii is made smaller, the moirée pattern will change, but the overall color is the same.

**Comment by svgeesus** [comment]
The rendered effect depends a lot on how much sub-pixel sampling is used. It tends to highlight numerical precision issues as well.

**Comment by PeterConstable** [comment]
If I take the SVG we used to generate the first radial gradient example (currently fig 5.13 in the annex), and update circle 0 to have the same center and radius as circle 1, the result in Chromium browsers looks like this;

![image](https://user-images.githubusercontent.com/26614869/101793626-dc57c600-3aba-11eb-9b55-27f056e40f61.png)

In Firefox, it looks like this:

![image](https://user-images.githubusercontent.com/26614869/101793460-b03c4500-3aba-11eb-8dd4-a9d417b7ee86.png)

The Firefox result is consistent with how I would interpret the algorithm, which the Chromium result is not.

But if the radii are just slightly different, then they are the same, and consistent with the algorithm (as expected). Here, the radii are set to 79 and 80:

![image](https://user-images.githubusercontent.com/26614869/101794227-80da0800-3abb-11eb-88a4-41116cba3de3.png)

Making the difference smaller—79.5 vs. 80—changes the Moiré pattern, as I'd expect:

![image](https://user-images.githubusercontent.com/26614869/101794618-e9c18000-3abb-11eb-8252-9bd56ab3dd72.png)

Those are as I'd expect. It's really just the case of circles being exactly the same that's in question.

**Comment by rsheeter** [comment]
Per f2f, test on svg (start/end swapped from colr) and canvas. Expected result is they do the same thing and we should specify consistent results.

**Comment by anthrotype** [comment]
I justed tested the degenerate radial gradient with two identical circles using HTML5 Canvas `createRadialGradient`. Unlike with the SVG tests that Peter posted above, which showed a difference in Chrome vs Firefox, with Canvas the identical circles just make the gradient disappear in both Chrome and Firefox (similarly to how Firefox renders the SVG with the identical radial gradient circles).

```
<!DOCTYPE html>
<html>
<body>

<canvas id="myCanvas" width="300" height="150" style="border:1px solid #d3d3d3;">
Your browser does not support the HTML5 canvas tag.</canvas>

<script>
var c = document.getElementById("myCanvas");
var ctx = c.getContext("2d");
var grd = ctx.createRadialGradient(75, 50, 50, 75, 50, 50);
grd.addColorStop(0, "blue");
grd.addColorStop(1, "red");
ctx.fillStyle = grd;
ctx.fillRect(0, 0, 300, 150);
</script>

</body>
</html>
```

https://www.w3schools.com/code/tryit.asp?filename=GN13XWLYG1MO

Slightly modiying the circle coordinates and radii make the gradient reappear again.

**Comment by anthrotype** [comment]
from "HTML Canvas 2D Context" at https://www.w3.org/TR/2dcontext2/

> If x0 = x1 and y0 = y1 and r0 = r1, then the radial gradient must paint nothing. Abort these steps.

**Comment by PeterConstable** [comment]
Duh!! We already state that:

> 1. If c₀ = c₁ and r₀ = r₁ then paint nothing and return.
