### ISSUE TITLE
Clarify expected behaviour of radial gradient transformed such that everything is flattened

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#151]
If the circles are flattened to _almost_ zero radius, there can still be significant distance between the centers. However, if circles are flattened to exactly zero, unless the direction of flattening was orthogonal to the direction between the centers, then the distance between the centers will also be flattened to zero: the circles and their centers will be colinear. Expected behaviour in this case isn't made clear.

Cf. #22, #150

**Comment by anthrotype** [comment]
In my testing with SVGs where a radial gradient is flattened (via gradientTransform) such that all coordinates are flattened onto a line (`gradientTransform="matrix(0.5 0.5 1.0 1.0 0 0)"`), the last color stop seems to win (in this case it's red).

https://codepen.io/anthrotype/pen/WNGqdrx

In the latter transformation matrix, [the determinant == 0 so it squishes all of space onto a line](https://youtu.be/Ip3X9LOh2dk?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&t=185).

If the determinant is not exactly 0, then we get those moire effects similar to those Peter noted in the other https://github.com/googlefonts/colr-gradients-spec/issues/150.

There is with ``gradientTransform="matrix(0.5 0.5 1.0 0.9 0 0)"`
https://codepen.io/anthrotype/pen/GRjbOVb

**Comment by PeterConstable** [comment]
Issue was addressed in @224. Closing.
