### ISSUE TITLE
array length at the start of an array at an offset is a departure from elsewhere in OT

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#16]
The proposed spec defines 

```cpp
template <typename T, typename Len=uint16>
struct ArrayOf
{
  Length count;
  T      array[/*count*/];
};
```
A consequence is that, if an array of records is referenced by offset, then the count is located at that offset.

There are several other places in the OT spec where there is an array of records at an offset. E.g.

CPAL: offsetFirstColorRecord, offsetPaletteTypeArray, offsetPaletteLabelArray, offsetPaletteEntryLabelArray
EBLC: indexSubTableArrayOffset
MERG: offsetToClassDefOffsets
STAT: offsetToAxisValueOffsets

In no case is the count for the array stored at the start of the array.

Moreover, storing the count at the start of the array can create redundancy and potential for inconsistency. For example, the arrays in CPAL all have the same count. If the count were stored separately for each array, that would create a possibility for inconsistency that doesn't exist by having a single occurrence of the count outside of the arrays.

Also, by changing this convention, we increase potential for confusion and for buggy implementations. (I stumbled over this myself.)

So, count for the BaseGlyphV1Records array should be in the CPAL header.

(Similarly, the definition for BaseGlyphV1Record needs to have numLayerV1Records as a field, and ColorLine needs to have numStops or numColorStops as a field. Those cases are structurally the same, so not quite the problem that exists for the BGRV1 array at an offset.)

**Comment by PeterConstable** [comment]
I wrote a v1 parser last night only to find out I have multiple bugs because I didn't pay close enough attention to this departure from past convention: I was following code that works for other tables and for COLR v0 assuming the same patterns, but ended up looking for BGV1 and LV1 array counts in the wrong places.

We shouldn't change from existing conventions unless there's really good reasons to do so.

**Comment by behdad** [comment]
Oh I meant to write that reply here; instead I wrote it at:

  https://github.com/googlefonts/colr-gradients-spec/issues/14#issuecomment-646166826

**Comment by PeterConstable** [comment]
This issue basically arose from confusion about what the base location is that offsets are relative to. It was resolved by determining that, in each case, offsets in an array are relative to the count field; and in each case the location of {count, array} is given by an offset in a parent table. This means that these structures fit existing patterns in the spec as *subtables*. All that's required is to document each of the structures in question as *tables*.

Closing.
