### ISSUE TITLE
Add discussion of well-formedness, validity

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#168]
5.7.11.1.8 currently covers acyclicity, and indicates that paints that introduce a cycle should be ignored.

I discussed with Rod adding something mentioning that a PaintColrGlyph expects a corresponding BaseGlyphV1Record, and we had in mind to say that if there wasn't a matching record then the paint should be ignored.

But it occurred to Rod that dropping a sub-graph might leave the remaining graph visually unbounded. So, perhaps rather than ignoring a sub-graph an implementation might need to ignore the entire graph. Our sense was that the best thing might be to say that implementations MAY ignore the graph. (If we don't mention it at all, it might not occur to implementers that there's an issue they should be considering.)

So, after adding the section on boundedness, find the right part of the spec to discuss this.

**Comment by rsheeter** [comment]
Per f2f, the color glyph is just invalid in several cases we say "ignored"

**Comment by PeterConstable** [comment]
Added: PR #183
