### ISSUE TITLE
names of the basic structures

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#17]
I'm wondering generally about the smaller, more basic structures: to what extent to define and name based on usage in this context versus naming more generally based on data types (and perhaps internal validation constraints).

Also, I'm thinking for structs that combine a basic type with a delta-set index the name should be prefixed with "Var" to reflect that.

* "Scalar": In this context Fixed is used to scale / as a coefficient. Other things could be scalars (e.g. F2Dot14), and Fixed could be used in other ways. An alternative name "VarFixed" would reflect the type without assuming how it's used.

* "NormalizedScalar": alternative possibility: "VarF2Dot14"
  * There is a variant used in Color that limits the range to [0, 1]. That's a different validation constraint. So, something like "VarF2Dot14Magnitude" (magnitudes are non-negative) could perhaps also be defined.

* "Position": since the type used in the template is FWORD, that does limit the context to design-grid values. Otherwise we could generalize to int16 and call it something like "VarInt16".
  * "Position" can suggest (x, y). I think "VarCoordinate" or "VarCoord" would be clearer.

* "Distance": similar to the previous item, use of UFWORD does limit the context to design-grid values. Otherwise, we could generalize to uint16 and call it something like "VarUint16".

* "Point": alternate suggestion "VarPoint"

* "Color": Incorporating "Var" here is trickier since there are two primary members, paletteIndex and transparency, and only the latter is variable. "ColorIndexVarAlpha" is a bit awkward but clear.

All the other structs in the proposal (ColorStop on up) are more complex. I wouldn't propose prefixing "Var" on any of those names.

**Comment by PeterConstable** [comment]
"color record" is a problem since that's already the name of a structure in CPAL. There are one or two cases in OT of different structures being given the same name, but i think it should be avoided.

**Comment by behdad** [comment]
Is there a documented or implied namespacing across different OpenType tables?  I've always assumed that individual tables define structures that are limited to the table itself, unless another table specifically "import"s them, eg. how CBDT refers to EBDT.  I'd love to clarify that in the spec and ideally apply consistently.

**Comment by PeterConstable** [comment]
There isn't a documented spec-wide namespace. But if possible I think it's preferable to avoid using the same name for different structures even if in the context of different parent tables. For example, it reduces confusion if someone does a search on the Web for _\<some struct name>_.

**Comment by behdad** [comment]
I agree that's generally desirable, yes.

You don't need to propagate the "Var" naming all the way out.  A FWORD plus a variation index can be called VarFWORD.  But from there on if you define a Point that has VarFWORD x and y, you shouldn't name that a VarPoint.

**Comment by behdad** [comment]
Maybe "Shade" for paletteindex+alpha.

**Comment by PeterConstable** [comment]
Perhaps, though in many contexts that deal with colour terminology, "shade" means darkening of a hue by mixing with black, while "tint" means lightening by mixing with white. Both imply reduction of saturation. 

Alpha does suggest less saturation if the background is achromatic. But they're really different concepts.

**Comment by behdad** [comment]
I forgot that you worked on colors. :))

**Comment by PeterConstable** [comment]
I think this has been adequately resolved. For draft OT 1.9 content, I'm proposing names as reflected in my OT formats draft, [here](https://github.com/PeterConstable/OT_Drafts/blob/master/COLR_V1/COLRv1formats_rev4.md).

Closing.
