### ISSUE TITLE
"transparency" vs. "opacity" vs. "alpha"

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#19]
The CPAL table uses "alpha", not "transparency".

CSS uses "alpha" in a context of specifying color values, e.g., ```rgba()```.  In other places, it uses "opacity".

* "transparency" would suggest that a value of 1.0 is fully transparent. 
* "opacity" would suggest that a value of 1.0 is fully opaque.

I believe the latter is intended. So, I suggest that field in the Color struct be renamed "opacity" or "alpha". I think "opacity" is clearer.

**Comment by anthrotype** [comment]
> "transparency" would suggest that a value of 1.0 is fully transparent.

That's how I interpreted in our current implementation. I believe it was intentionally named "transparency" so that the default opaque case would be encoded as 0.0, and zeros are compressed away more easily.
But I'd also like to hear from @behdad on this one.

**Comment by behdad** [comment]
My fault.  Should say "opacity" indeed.  Or for more clearance just "alpha".  Cairo has had "paint_with_alpha" in API and never caused any confusion for anyone.

**Comment by behdad** [comment]
[When this separate alpha was brought up before, I forgot to mention that this also enables "foreground with opacity" that was not possible before.]

**Comment by rsheeter** [comment]
To me OT consistency within OT is more important. If CPAL uses alpha we should default to using alpha.

**Comment by behdad** [comment]
agree

**Comment by PeterConstable** [comment]
Has since been resolved. Closing.
