### ISSUE TITLE
Clarify the description of the linear gradients

### ISSUE THREAD

**Issue by vlevantovsky** [googlefonts/colr-gradients-spec#196]
In the proposed new sub-clause 5.7.11.1.2.2 "Linear Gradients", the second paragraph is as follows:

> An additional point, p₂, is also used to rotate the gradient orientation in the space on either side of the line defined by p₀ and p₁. The vector from p₀ to p₂ can be referred to as the rotation vector. If the rotation vector is colinear with the line p₀p₁, there is no rotation: colors in the space on either side of the line p₀p₁ extend in the perpendicular direction. But if the rotation vector is not colinear, the gradient is drawn skewed by the angle between p₀p₁ and p₀p₂.

I find the use of the term "colinear" very confusing when it is applied to "rotation vector". The term "colinear" is commonly used to define points that belong to the same line. In our case, when we have three points p₀, p₁, and p₂ that define two vectors  p₀p₁ and p₀p₂ - the fact that points p₀, p₁, and p₂ may be colinear (i.e., belong to the same line) doesn't say anything about _directions_ of the two vectors p₀p₁ and p₀p₂. These vectors may have the same direction when colinear points on the line positioned in sequence (p₀, p₁, p₂) or (p₀, p₂, p₁) , but the same two vectors would have opposite directions if colinear points positioned in sequence (p₂, p₀, p₁) or (p₁, p₀, p₂). I would suggest to rephrase the wording of the second paragraph to clarify that it is the difference in *directions* between two vectors p₀p₁ and p₀p₂ that determine the angle with which the gradient is skewed. 

Also, it is not clear [neither from the description nor from examples that follow] what should be the result of rendering a linear gradient when the skew angle is more than 90 degrees (should the color line direction be reversed?). It may also be worth mentioning what role (if any) the magnitude of the "rotation vector" plays in determining linear gradient rotation. Currently, the description is silent about it, and it appears (as illustrated by figures 5.12 - 5.14) that the magnitude of rotation vector has no effect.

**Comment by anthrotype** [comment]
(I paste this below as a reminder to myself, I'll elaborate more later)

https://github.com/googlefonts/nanoemoji/blob/885d8c6e6410403bc37d67e9aa6803f83419702b/src/nanoemoji/svg.py#L188-L199
```python
    # P2 allows to rotate the linear gradient independently of the end points P0 and P1.
    # Below we compute P3 which is the projection of P1 onto the line between P0 and P2
    # (aka the "normal" line, perpendicular to the linear gradient "front"). The vector
    # P3-P0 is the "effective" linear gradient vector after this rotation.
    # When P2 is collinear with P0 and P1, then P3 (projection of P1 onto the normal) is
    # == P1 itself thus there's no rotation. When P2 sits on a line passing by P0 and
    # perpendicular to the P1-P0 gradient vector, then this projected P3 == P0 and the
    # gradient degenerates to a solid paint (the last color stop).
    # NOTE: in nanoemoji-built fonts, this point P3 is always == P2, so we could just
    # use that here, but the spec does not mandate that P2 be on the "front" line
    # that passes by P1, it can be anywhere, hence we compute P3.
    p3 = p0 + (p1 - p0).projection(p2 - p0)
```

**Comment by PeterConstable** [comment]
#207 provides revisions for this.

**Comment by PeterConstable** [comment]
This has been addressed, so closing.
