### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by drott** [googlefonts/colr-gradients-spec#2]
Add examples for a full glyph, consisting of several layers, using a variety of gradients.

**Comment by rsheeter** [comment]
Do you think a more technical version of the examples for IUC 44 might work?

**Comment by behdad** [comment]
> Do you think a more technical version of the examples for IUC 44 might work?

Oh. Is the video / slide deck available yet?

**Comment by drott** [comment]
> Do you think a more technical version of the examples for IUC 44 might work?

Yes, I was thinking about that, too. Now that we a few more known examples, I can turn them into something more technical for the spec.

**Comment by PeterConstable** [comment]
Given the examples that I've added for specific details, is a comprehensive example still needed?

(If so, I wouldn't suggest trying to visualize the entire graph. It could be presented similar to [GSUB examples](https://docs.microsoft.com/en-us/typography/opentype/spec/gsub#gsub-subtable-examples), for instance: a visual of the complete color glyph and a table showing the data structures.)

**Comment by PeterConstable** [comment]
@drott : Do you think more examples are needed?

**Comment by drott** [comment]
I think we have a sufficient set of examples now showing the interaction and nesting of Paints.
