### ISSUE TITLE
Affine2x2 at offset or in sequence?

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#20]
The Affine2x2 is record-like in having a fixed size (though there's not an array of them). This spec makes it table-like in being referenced at an offset from its parent. Any particular reason why it wasn't just embedded in sequence within its parent?

**Comment by anthrotype** [comment]
I guess because it's optional and can be omitted.

**Comment by PeterConstable** [comment]
Makes reasonable sense. Thx
