### ISSUE TITLE
abrupt change as radial gradient circle moves from/to contained within/external to other circle

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/colr-gradients-spec#204]
Consider a COLRv1 variable font with a radial gradient in which the start circle's centre point (c0) moves from being outside to being inside the end circle or viceversa. It would look like the following SVG animation:

https://user-images.githubusercontent.com/6939968/104179575-f7905b00-5403-11eb-9d8a-f27871bafc44.mp4

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="300" height="600">
<defs>
<radialGradient id="grad" cx="50%" cy="50%" r="30%" fx="50%" fy="50%" fr="10%">
	<animate attributeName="fx" values="-2.5%;102.5%;-2.5%" dur="6s" repeatCount="indefinite" begin="0s"/>
    <stop stop-color="#FFDB80" offset="0%"/>
    <stop stop-color="#FF791F" offset="50%"/>
    <stop stop-color="#E09F00" offset="100%"/>
</radialGradient>
</defs>
<rect width="300" height="300" fill="url(#grad)"/>
</svg>
```

So, there is a very stark change as one circle goes from being inside to being outside the other, as you can see. 
It's as if I'm looking at the interior surface of a hollow 3D cone that's pointing away from me; then as the cone (or my point of view) rotates with the tip now lying outside the circle, I find myself outside the cone looking at its exterior surface.
Intuitively I would have tought this imaginary cone to point towards me, and that I'd always look at it from the outside, thus avoiding the abrupt change at the boundary.

In any case, I think the current behavior is intentional and by design, as it appears consistent with the way HTML Canvas createRadialGradient and SVG2 specify radial gradients, as well as the way implementation work in this situation (the animation above is taken from Google Chrome).

However, I was actually not aware of this until I stumbled on a bug in our COLRv1 compiler where, because of some rounding issue, one circle centre that in the input SVG was exactly on the perimeter of the other circle, ended up shifting to being outside in the compiled COLRv1 table, producing an unexpected incorrect rendering (https://github.com/googlefonts/picosvg/issues/158).

Honestly I don't know if this is or would become a problem, I simply wanted to highlight this here in case others think we should address this somehow.

**Comment by anthrotype** [comment]
Hm. It just occurred to me that one could simply swap the two circles (make the start circle the end circle and viceversa) and thus make so that the "imaginary cone to point towards me". Below is the same animation where I swapped the circles centres and radiuses, and also inverted the order of the color stops:

https://user-images.githubusercontent.com/6939968/104316511-7c4aaa00-54d4-11eb-9bdb-987dc72cfff5.mov

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="300" height="600">
<defs>
<radialGradient id="grad" fx="50%" cy="50%" r="10%" fx="50%" fy="50%" fr="30%">
	<animate attributeName="cx" values="-2.5%;102.5%;-2.5%" dur="6s" repeatCount="indefinite" begin="0s"/>
    <stop stop-color="#E09F00" offset="0%"/>
    <stop stop-color="#FF791F" offset="50%"/>
    <stop stop-color="#FFDB80" offset="100%"/>
</radialGradient>
</defs>
<rect width="300" height="300" fill="url(#grad)"/>
</svg>
```

**Comment by anthrotype** [comment]
OK since one can achieve both effects by simply choosing which circle is start or end, I consider this a non issue. If we think it may help, we could add an example where c0 and c1 are not contained within one another -- similar to figure 5.15  -- but where c0 is _larger_ than c1 (r0 > r1).

**Comment by vlevantovsky** [comment]
I think your findings deserve a couple of sentences in the spec.

**Comment by PeterCon** [comment]
This reflects my thought that the best name for this type of gradient would have been "cylindrical": the gradation is on the surface (inside or outside) of a cylinder, which collapses to a cone at one end if the circles have different radius. With that understanding, the behaviour you've encountered is completely expected. 

>If we think it may help, we could add an example where c0 and c1 are not contained within one another -- similar to figure 5.15 -- but where c0 is larger than c1 (r0 > r1).

That would be figure 5.22.

**Comment by anthrotype** [comment]
> That would be figure 5.22.

oh thanks! I somehow skipped over that one. I guess we can now close this then.

**Comment by PeterCon** [comment]
Since Vlad suggested a mention of the behaviour you called out in a variable font, I'm drafting a short addition.

**Comment by PeterConstable** [comment]
The transition point comes when the inner circle's circumference just touches the outer circle's circumference. Here's an example of what that would look like (using the repeat extend mode).

![image](https://user-images.githubusercontent.com/26614869/104359755-eb200700-54c4-11eb-99c7-66d968734436.png)

**Comment by anthrotype** [comment]
Yes, it is enough to have `r0 + distance(C0, C1) > r1` to trigger the abrupt transition (in the image above I think it is exactly `== r1`).
Note that if you invert start and end circles and you have C0 (start circle) containing C1 (end circle), then there is no abrupt transition even when `r1 + distance(C0, C1) > r0`

**Comment by PeterConstable** [comment]
There will still be an abrupt transition. It would be effectively equivalent to reversing the color line, but no other change. 

Consider: the algorithm only paints the circles extrapolated from c0 and c1. If there is one point on c0 touching c1 (coincident points), then all of the extrapolated circles will pass through that point, and nothing on the outside (projecting radially from the centers) will ever get painted.
