### ISSUE TITLE
Missing Porter-Duff plus

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#208]
In reviewing modes for #205 I seem to be seeing we are missing https://www.w3.org/TR/compositing-1/#porterduffcompositingoperators_plus.

I think I omitted because core graphics didn't offer an enum for it. Cairo, Skia, and D2D appear to have it. In retrospect I think probably we should include it.

**Comment by behdad** [comment]
Agree.

**Comment by PeterConstable** [comment]
Does it actually add any functionality? IIUC, it would be the same as simple alpha blending that can be achieved using PaintColrLayers instead of PaintComposite.

**Comment by behdad** [comment]
> Does it actually add any functionality? IIUC, it would be the same as simple alpha blending that can be achieved using PaintColrLayers instead of PaintComposite.

That's the SourceOver operator. This is different.

**Comment by PeterConstable** [comment]
Ah, yes, you're right.

**Comment by rsheeter** [comment]
After this I believe the only W3 composite mode we lack is the "no blend" blend https://www.w3.org/TR/compositing-1/#blendingnormal. That one I don't immediately see reason to add.

**Comment by behdad** [comment]
> After this I believe the only W3 composite mode we lack is the "no blend" blend https://www.w3.org/TR/compositing-1/#blendingnormal. That one I don't immediately see reason to add.

Yep. That's what our SourceOver does.

In W3C model, the PorterDuff composition operators are orthogonal to the blending mode. That is, you can have any arbitrary composition operator with any arbitrary blending mode. In most libraries though, this separation is not kept and the blending modes have an implied SourceOver composition operator. Hence the normal blending mode is simply the SourceOver in our model.
