### ISSUE TITLE
would Point-less be better?

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#21]
In every 2D graphics spec I've looked at today (HTML canvas, PDF, Skia, Direct2D), I've noticed that linear, radial and conical gradients are specified using separate coordinates, "x0, y0, x1, y1" rather than combining xy pairs into structs. (GDI was different in that regard.)

Would it be better if, instead of defining a Point struct we just used a pair of VarFWords instead? (One less struct to document, and more similar to current 2D graphics APIs.)

**Comment by behdad** [comment]
Agree.

**Comment by PeterConstable** [comment]
I've created a [rev2 format description](https://github.com/PeterConstable/OT_Drafts/blob/master/COLR_V1/COLRv1formats_rev2.md) that reflects that.

**Comment by PeterConstable** [comment]
If we make that change, should the order in PaintFormat3 remain (x0, y0, x1, y1, r0, r1)? Or should it change to be like what is typical in APIs and in PDF, (x0, y0, r0, x1, y1, r1)?

**Comment by behdad** [comment]
The latter sounds better to me as well.

**Comment by PeterConstable** [comment]
OK. 

It would be good to have the doc in this repo updated as well as a new rev (preferably IMO a new, second file) of noto-handwriting-COLR_1.

**Comment by PeterConstable** [comment]
When tools and test font do change, it would be a good time to decide on whether to continue with 16-bit glyph IDs or go to 32-bit.

**Comment by anthrotype** [comment]
Thanks Peter for taking the time to write those drafts, and apologies for the radio silence.
I can now work on updating the fonttools implementation and rebuild the test font according your rev3 -- or rev4 if we also include the 32-bit glyphIDs.
Could you send a PR to update the md document in this repo based on those drafts or yours?
Thank you.

**Comment by anthrotype** [comment]
I made a PR to change the fonttools implementation following @PeterConstabl's [rev3 doc](https://github.com/PeterConstable/OT_Drafts/blob/master/COLR_V1/COLRv1formats_rev3.md)

https://github.com/fonttools/fonttools/pull/2008

Here you can find updated test fonts rebuilt with this: https://github.com/googlefonts/color-fonts/tree/colrv1-rev2/fonts

**Comment by PeterConstable** [comment]
There was consensus on a design change, implemented in fonttools prototype. Closing.
