### ISSUE TITLE
provide example of radial gradient with degenerate transform

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/colr-gradients-spec#22]
Radial gradients can contain a 2x2 affine matrix to transform the two circles into ellipses, but _without affecting the position of their centres_ -- unlike SVG's `gradientTransform`, or "graphics systems like Skia or Cairo that apply their (often called user-) transformation matrix to everything".
When rendering CORLv1 radial gradients using the latter graphics systems, one should thus apply the _inverse_ matrix to the centres' coordinates to undo the effect of applying the matrix to everything.
But of course some matrices are singular or degenerate (with 0 determinant) and cannot be inverted.
 
The draft spec notes that even these have a "well defined shape", however it is not clear to me what this shape should look like. A visual example could help a lot here.

This is the relevant paragraph:

> Note: Implementations must be careful to properly render radial gradient even if the provided affine matrix is degenerate or near-degenerate. Such radial gradients do have a well-defined shape, which is a strip or a cone filled with a linear gradient. Implementations using the inverse-transform approach noted above can fall back to a linear-gradient combined with a clipping path to achieve proper rendering of problematic affine transforms.

**Comment by anthrotype** [comment]
I'm still trying to figure out what this sentence actually means:

> Implementations using the inverse-transform approach noted above can fall back to a linear-gradient combined with a clipping path to achieve proper rendering of problematic affine transforms

**Comment by behdad** [comment]
> But of course some matrices are singular or degenerate (with 0 determinant) and cannot be inverted.
> 
> The draft spec notes that even these have a "well defined shape", however it is not clear to me what this shape should look like. A visual example could help a lot here.

> I'm still trying to figure out what this sentence actually means:
> 
> > Implementations using the inverse-transform approach noted above can fall back to a linear-gradient combined with a clipping path to achieve proper rendering of problematic affine transforms

This:
![image](https://user-images.githubusercontent.com/142891/86502438-f0eba180-bd57-11ea-98f0-fb0b457f1ff0.png)

Top row is where there's no translate, so we have two circles. The middle row is where there's a transformation matrix that is not degenerate (ie. determinant > 0). The last row is the degenerate case where the ellipse collapses into a line. Now since the two ellipses use the same transformation matrix, it follows that the two lines are parallel, which makes the resulting gradient a linear gradient. The shape of the sides can be enforced using clipping. That's what we mean by "fall back to a linear-gradient combined with a clipping path to achieve proper rendering of problematic affine transforms."

[The examples use a repeat mode that stops the rendering at the two sides. I believe we intended to allow different modes but current wording of the step doesn't suggest that.]

Hope that helps.

**Comment by anthrotype** [comment]
Yes, that makes sense now, thank you! We should add something like that to the draft spec.

**Comment by rsheeter** [comment]
Per f2f discussion:

Radial gradients
  if both radius are 0 no rendering
    TODO specify this
  if centers are distinct
    if one radius is 0 and one is non-0 we have a triangle
      this is clear from examples
  if centers are the same
    if one radius is 0 and one is non-0 then well defined

  TODO add an example with one circle inside the other

@drott is this something you can take?

**Comment by drott** [comment]
> @drott is this something you can take?

Yes, I'll work on this.

**Comment by PeterConstable** [comment]
[Behdad's comment above](https://github.com/googlefonts/colr-gradients-spec/issues/22#issuecomment-653704166) illustrated how a linear gradient could result in one case of a degenerate transform. But it doesn't cover all cases: his drawing shows the circles flattened in the same direction as the line from c0 to c1. The result is that the circles are flattened to lines that are perpendicular to the line c0-c1.  Of course, the circles could be flattened to lines that aren't perpendicular to c0-c1, and things would still work.

But what if the circles were flattened such that the resulting lines are parallel to c0-c1? (That would be like having (p2-p0) · (p1-p0) = 0 for a linear gradient.)

**Comment by PeterConstable** [comment]
Also, if the diameter of the circles in the direction from c0 to c1 is shortened, then so is the distance between c0 and c1. 

What was described above considered a situation in which the circles could be transformed without affecting the placement of the circles. But that's not how the current formats work: if a PaintRadialGradient is nested under a PaintTransform, then the radii and the centers are transformed the same way.

**Comment by PeterConstable** [comment]
We made some changes some months ago after discussing transforms that result in degenerate cases for gradients, and there's been no additional discussion in this issue for over six months. So, assuming this can be closed.
