### ISSUE TITLE
Need a note re bounding box placeholder glyph under transforms

### ISSUE THREAD

**Issue by drott** [googlefonts/colr-gradients-spec#229]
From the implementation experience with Skia and FreeType, it may be worthwhile pointing out in a note the following:
Imagine a slanted or rotated representation of sequence of glyphs of a COLRv1 font on a canvas:
When we have a two-point degenerate contour placeholder glyph spanning a bounding box, it is this imagined rectangular bounding box that needs to be transformed to have the bounding box for the transformed color glyph. If you compute the bounding box from just the two points transformed, the bounding box ends up too small.

**Comment by rsheeter** [comment]
Per f2f, suggest explicitly commenting you either need enough space for all variations or to vary the bbox itself

**Comment by PeterConstable** [comment]
#255 merged. Closing
