### ISSUE TITLE
Provide a way to opt out of variations

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#233]
In https://github.com/googlefonts/nanoemoji/pull/233 I've been playing with counting overhead for variation indices. I've also rigged a branch of FontTools [w/help from @anthrotype] to compile with all the variation constructs removed (https://github.com/fonttools/fonttools/compare/novar_colrv1) and test compiled Noto.

| emoji set | format | size w varidx | size w/o varidx | delta |
| --------- | ------ | ----- | -------------- | ----- 
| Noto | ttf | 3784340 | 3300004 | -484336 (-12.8%) |
| Noto | woff2 | 1251284 | 1228628 | -22656 (-1.8%) |

woff2 performs brilliantly :) However, for a font in a system image 473KB (12.8%) is enough to care.

So, is there an easy way to avoid paying for variation when you don't need it? - one immediate thought is to "spend" the high order bit (EDIT: this was a bad idea! - better to just designate formats and not burn a bit per comments) of format to indicate use of variations. If defining variable and non-variable structures separately one would end up with something like:

```C++
struct Affine2x3
{
  Fixed xx;
  Fixed yx;
  Fixed xy;
  Fixed yy;
  Fixed dx;
  Fixed dy;
};
struct VarAffine2x3
{
  VarFixed xx;
  VarFixed yx;
  VarFixed xy;
  VarFixed yy;
  VarFixed dx;
  VarFixed dy;
};
struct PaintTransformed
{
  uint8               format; // = 8
  Offset24<Paint>     src;
  Affine2x3           transform;
};
struct VarPaintTransformed
{
  uint8               format; // = 136 (8 | 0x80)
  Offset24<Paint>     src;
  VarAffine2x3           transform;
};
```

Doubtless other options, perhaps better ones, exist

**Comment by PeterConstable** [comment]
Who needs more than 127 paint formats (or more than 640K)?

There are certainly other cases in OT where you need to start reading a table, get to a flag field and then use that to determine how to read the remainder of the table. Putting the flag into the format byte allows you to get that info up front while reading the format byte. 

But what does it really buy? Effectively, instead of possibility for 255 formats with (say) formats 8 and 13 being VarPaintTransformed and PaintTransformed, you would end up with a possibility of 127 variable formats and 127 corresponding non-variable formats, with format 8 being VarPaintTransformed and format 135 being PaintTransformed. You're still going to want to define Affine2x3 and VarAffine2x3, (and VarColorIndex/ColorIndex) won't you?

**Comment by PeterConstable** [comment]
Which would be better?

* PaintTransformed & VarPaintTransformed
* PaintTransformed & PaintVarTransformed

I think I'd be inclined to have names for all paint formats use the pattern Paint*.

**Comment by PeterConstable** [comment]
In the Noto font you tested with (the version with the var index fields), would it be possible to get a count of the # of occurrences of each type of structure directly containing a var index field, or the count for each format of paint table?

* PaintLinearGradient (VarFWord x 6)
* PaintRadialGradient (VarFWord / VarUFWord x 6)
* PaintSweepGradient (VarFWord / VarFixed x 6)
* PaintTranslate (VarFixed x 2)
* PaintRotate (VarFixed x 3)
* PaintSkew (VarFixed x 4)
* ColorIndex (VarF2Dot14 x 1)
* ColorStop (VarF2Dot14 x 1)
* Affine2x3 (VarFixed x 8)

Affine2x3 seems relatively costly with 8 Var* members. But each Paint*Gradient starts with 6 Var* members _before counting color stops_, and each color stop will add another two Var* members.

**Comment by rsheeter** [comment]
To your point there are already formats that don't need a Var/NonVar distinction; for those the ability to mark variable vs not variable is wasted. Looking at them one by one:

* PaintColrLayers - only one format
* PaintSolid - needs 2 formats (a static and a variable)
* PaintLinearGradient - needs 2
* PaintRadialGradient - needs 2
* PaintSweepGradient - needs 2
* PaintGlyph - only one
* PaintColrGlyph - only one
* PaintTransformed - needs 2
* PaintTranslate, PaintRotate, PaintSkew - debatable. One could argue these were added specifically to facilitate variation ... but they also save bytes. I think I lean toward needs 2.
* PaintComposite - only one

I think that means paying per format costs us 8 formats while paying a whole bit costs 128. Let's forget about spending a bit :)

**Comment by anthrotype** [comment]
I vote for additional `PaintVar*` formats (without using the high bit).

**Comment by drott** [comment]
If we do bring down the uncompressed font size with COLRv1 already compared to the CBDT/CBLC font, and given the good results after woff2 I am not 100% convinced it's worth the complexity. Would this be preferable to have really on a `Paint*` level-granularity or would rather something like a global or higher-up setting be sufficient to say: This COLR table is not variable at all? Then we could potentially interpret all Var* data structures conditional on such a setting. - or is that too hacky?

**Comment by PeterConstable** [comment]
There are precedents in OT for structures with alternate formats. In general the data determining the structure is as local as possible. E.g., in GPOS lookup subtables, such as [type 1, format 1](https://docs.microsoft.com/en-us/typography/opentype/spec/gpos#lookup-type-1-single-adjustment-positioning-subtable), the ValueRecord has multiple optional fields, and the ValueFormat field that immediately precedes it has flags that determine which ValueRecord fields are present. A remote conditioning factor, such as a flag in the parent COLR table or a heuristic like absence of an ItemVariationStore can be a nuisance in implementations since information from higher in the structure hierarchy needs to be passed down and maintained. 

There are certainly cases of remote values, like numGlyphs in the maxp table affecting how data is read in other places, though even for that there are instances of it being copied so that a more local value can be read. So, whereas in the 'loca', 'hdmx' and 'hmtx' tables maxp.numGlyphs is referenced, in the 'post' table there is a copy.

@anthrotype probably has opinions on this.

**Comment by anthrotype** [comment]
> A remote conditioning factor... can be a nuisance in implementations

it would make parsing/building the Paint tree a bit more cumbersome -- not impossible. One would need to maintain a state "are we in a variable COLR" and parse/build accordingly. Each variable-enabled paint would be like two formats in one, with or without VarIndices. I think I still prefer the simplicity of distinct PaintVar formats, but I can be swayed in the other direction.

**Comment by rsheeter** [comment]
I think we should aim for pay for what you use. A global (table-wide) toggle means that having any variation in COLR (I've got *one* animated rotation!) doubles (for napkin math) the size of the table. IMHO that makes a global toggle a no-go.

I did think about a per-glyph toggle, such as the base glyph flagging does/does not use variations but I think it works out much more cleanly in implementation to just introduce specific paints:

* If one is doing a per-field parser you can easily read both PaintT and PaintVarT into the same structure
   * Parse the non-variable format into the same structure as the variable format with nop var indices
* If you are like FontTools or HarfBuzz and you just declare structures and have a generic read/write (this isn't true for the COLR builder code but I think we can work to reduce the specialized code) individual formats work beautifully
* A font compiler can produce the most optimal output, pay for exactly what you used with the most possible reuse of parts
   * You don't have cases like two glyphs use the same construct but one of them is globally variable so it has to make an extra copy of the Paint with unused var indices in it

I understand it's a pita to have to suddenly add up to 8 more paints but I think the end result is worth it.

**Comment by PeterConstable** [comment]
I'm in process on sync'ing the OT draft back up with the OFF draft. After that, I'll prepare a PR adding additional paints (probably have that tomorrow).

Shall I renumber paint formats to keep non-var/var pairs together?

E.g.,
* Format 2: PaintSolid
* Format 3: PaintVarSolid
* Format 4: PaintLinearGradient
* Format 5: PaintVarLinearGradient
* etc.

**Comment by anthrotype** [comment]
Renumbering format numbers is also a pita

**Comment by rsheeter** [comment]
> Renumbering format numbers is also a pita

I can do it for FontTools if you like; I feel like this particular pita could be considered my fault :D

**Comment by drott** [comment]
I am really concerned about the amount of bloat and duplication that will add to the spec by repeating every Paint with `Var*` and non-var structs. That does not seem like a good design to me.

> However, for a font in a system image 473KB (12.8%) is enough to care.

Can we shed some more light on the "enough to care" conclusion? Our assumption is that we bring down the font size for the Noto Color Emoji example quite significantly. A fifth without flags (8 -> 1,5MB) maybe still to 3/4 or 1/2 with flags in the font. Why are the extra savings needed?

If I am not mistaken, firmware fonts in the system image are read-only and in the case of the Android zygote process implementation are a read-only memory area that is shared among processes cloned from the Zygote. In other situations, when accessing a file from the firmware image, the file can be mmap'ed directly from firmware read-only storage. For OTA updates or similar, the images are most likely compressed as well. Where would still be a pain point that would be addressed by the extra savings of the uncompressed size? 

I would like to understand this better before we introduce all the extra overhead.

**Comment by vlevantovsky** [comment]
I too would like to understand better where the savings are coming from. It's hypothetically possible that we can have variation-capable data structures and no variation data in a font, vs. another font that does have variations. If the major part of savings that makes it "enough to care" comes from the lack of variation data - how much extras can be saved by creating two sets of tables that only differ in their abilities to support variable fonts?

**Comment by PeterConstable** [comment]
In Rod's data above, the 12% difference is overhead for being variation-capable, not actual variation data.

Suppose there were two COLR v1 proposals with the same graphic capabilities, neither supporting variation, but one being 12% less size efficient. Clearly we'd opt for the smaller one (other considerations being equal).

Now we have two COLR v1 proposals, A and B, with the same graphic capabilities, and both supporting variations. For non-variable fonts, B is (on average) 12% more size efficient than A; and for variable fonts, B is 0% to 12% more size efficient than A, depending on how many elements with color glyph definitions have variations.

**Comment by PeterConstable** [comment]
I've started PR #249, which shows the additional formats needed for paint-level granularity of control (var indices or no var indices).

**Comment by rsheeter** [comment]
> where the savings are coming from
> how much extras can be saved by creating two sets of tables that only differ in their abilities to support variable fonts?

Consider a structure like Affine2x3. Six Fixed fields costs you 24 bytes. Adding a variation index for each costs you 24 more. There is no way to not pay those bytes even if you know your specific Affine2x3 isn't variable. Carry this through just about every structure in the COLR v1 spec and you end up with a COLR table for Noto that is almost half variation indices. The cost is noticeable even against the size of the overall font.

> Why are the extra savings needed?

Android is the best concrete example. We go to pretty significant lengths to squeeze bytes out of the system image. As an example, https://github.com/googlefonts/fontcrunch was written for this very purpose. 

It costs us a bit of work now and we get more compact COLR fonts forever. If a user has some parts of their COLR font vary they will pay only for the parts that vary, no fixed penalty globally imposed.

**Comment by rsheeter** [comment]
@anthrotype recompiled our demo fonts; https://github.com/googlefonts/color-fonts/pull/46/files makes me very happy :)

![image](https://user-images.githubusercontent.com/6466432/107990031-607d6c80-6f88-11eb-88fd-52fdc389cdfd.png)

**Comment by rsheeter** [comment]
Spec changes made in https://github.com/googlefonts/colr-gradients-spec/pull/249, https://github.com/googlefonts/colr-gradients-spec/pull/252. Closing.
