### ISSUE TITLE
On extend mode

### ISSUE THREAD

**Issue by behdad** [googlefonts/colr-gradients-spec#25]
There are multiple issues and wrong wording and wrong images and inconsistency about how we wrote this. Dominik and I thought about it extensively (at least half a day at the whiteboard) and we did reach a good solution. It just seems like we failed writing that correctly.

I'm a bit busy right now but within a few days I will fully describe all the issues and make recommendation.

https://github.com/googlefonts/colr-gradients-spec#extend-mode

![image](https://user-images.githubusercontent.com/142891/86502537-38bef880-bd59-11ea-883d-b4f61ab2fdfe.png)

![image](https://user-images.githubusercontent.com/142891/86502540-407e9d00-bd59-11ea-866d-f56d66a75703.png)

**Comment by PeterConstable** [comment]
IIUC, with changes made in the months since this was opened, there are no outstanding issues, so closing. If there are, please re-open with details.
