### ISSUE TITLE
phantom points not used for bbox

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#256]
In *5.7.11.1.8.2 Metrics and boundedness of color glyphs using version 1 formats*, do we need to clarify that rasterizer phantom points are not considered?

**Comment by rsheeter** [comment]
@drott wdyt? - my gut reaction is we don't need to

**Comment by drott** [comment]
I tend to agree, is there a precedent in terms of speaking about bounding boxes of contours in other cases?

**Comment by PeterConstable** [comment]
Concluding it's not necessary. Closing.
