### ISSUE TITLE
Too terse to too verbose

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#275]
At one point the COLR v1 spec was so terse multiple people misunderstood. Now we have several reports it's too verbose. Perhaps we might try to find a happy middle ground or more clearly distinguish explanatory content from spec.

**Comment by vlevantovsky** [comment]
Were any specific pointers made to a piece of content that is "too verbose"? in the preparation for an upcoming meeting, I've been doing multiple rounds through the text of the amendment, and I think we strike a good balance between "strictly spec" and "good to know" parts.

**Comment by davelab6** [comment]
One issue may be that they are interleaved and could be sectioned out

**Comment by PeterConstable** [comment]
>One issue may be that they are interleaved and could be sectioned out

In OFF, clause 5.7.11 will cover the COLR table, so we're talking about sections under that. 

Clause 5.7.11.1 has all the conceptual explanation of graphics capabilities plus some other details: 
1) Colors and solid color fills
2) Gradients
3) Filling shapes
4) Layering
5) Transformations
6) Compositing & blending
7) Re-use
8) Glyph metrics & boundedness
9) Color glyphs as a directed acyclic graph

Clause 5.7.11.2 has all of the formats, and only the formats.

Clause 5.7.11.3 has the colrv1 rendering pseudo-code.

Clause 5.7.11.4 discusses variations.

The next edition of OFF will have a TOC that includes all of these sections (and their subsections that I haven't listed).

The OT spec will have TOC links corresponding to these next-level headings (5.7.11.1, 5.7.11.2, 5.7.11.3 and 5.7.11.4).

OFF will have cross-references / OT will have links between these sections for relevant details.

Now, some portions of 5.7.11.1 go beyond conceptual explanation to include some requirements, particularly the specifics on gradients, and the last two sub-sections on metrics/boundedness and the DAG. I don't think there's a better way to organize the specifics on gradients. Maybe the parts on metrics/boundedness and the DAG could be moved later, perhaps combined with the section with the pseudo-code. But it's not clear to me there's really a problem with those two sub-sections.

In F2F discussion with Rod, Dominik and Cosimo, it wasn't clear to us there was an easy or obvious improvement.

**Comment by rsheeter** [comment]
I still feel like something isn't quite right about the presentation - it's a bit of a yellow flag that the part I find myself referring to is the C++ structs, which are much much more concise - but I've failed miserably to come up with a concrete improvement. Closing, please reopen provided there is a concrete suggestion for how to improve.
