### ISSUE TITLE
PaintScale?

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/colr-gradients-spec#279]
There is PaintRotate and PaintSkew, each with an explicit center point. PaintScale with an explicit center point would be equally useful.

I know it can be emulated by stacking PaintTranslate and PaintTransform, but that takes up more space and is less convenient.

```cpp
struct PaintScale
{
  uint8                  format; // = ??
  Offset24<Paint>        src;
  Fixed                  scaleX;
  Fixed                  scaleY;
  Fixed                  centerX;
  Fixed                  centerY;
};
```
But of course it would be most useful in its `PaintVarScale` counterpart.

**Comment by horasio** [comment]
It might not be super useful for emojis, but is essential, I think, for the use case presented by the "variable component" proposal of Just and Jérémie.

**Comment by justvanrossum** [comment]
I think @behdad gave this an informal +1 in a f2f the other day. Would love that confirmed.

**Comment by justvanrossum** [comment]
Another variant:
```cpp
struct PaintScaleProportional
{
  uint8                  format; // = ??
  Offset24<Paint>        src;
  Fixed                  scale; // for both x and y
  Fixed                  centerX;
  Fixed                  centerY;
};
```
Plus `PaintVarScaleProportional`.

Or: `PaintScaleXY` `PaintVarScaleXY` and use `PaintScale` and `PaintVarScale` for the proportional one.

Hmhm, ideally you want all fields to be optional: it minimally has to have a single `scale` field.

**Comment by behdad** [comment]
Yes I was telling Rod et al yesterday that something like this is desirable. Ideally:

* Uniform scale or separate X/Y,
* Centered around origin or center provided,
* No variations or variations.

We can call that 8 different paints, or define in terms of bits of the format.

Same for PaintRotate, PaintSkew. I think their center should also be optional.

**Comment by justvanrossum** [comment]
> Is stacking be preferable to computing the 2x3 to scale relative to some center? I suppose it might be under variation?

Variation is the sole reason a center is needed.

**Comment by justvanrossum** [comment]
> We can call that 8 different paints, or define in terms of bits of the format

Yes, it can easily be both:
```
PaintScale = N + 0
PaintScaleVar = N + 1
PaintScaleCenter = N + 2
PaintScaleCenterVar = N + 3
PaintScaleUniform = N + 4
PaintScaleUniformVar = N + 5
PaintScaleUniformCenter = N + 6
PaintScaleUniformCenterVar = N + 7

PaintRotate = N + 0
PaintRotateVar = N + 1
PaintRotateCenter = N + 2
PaintRotateCenterVar = N + 3

PaintSkew = N + 0
PaintSkewVar = N + 1
PaintSkewCenter = N + 2
PaintSkewCenterVar = N + 3
```

**Comment by justvanrossum** [comment]
So, while I'm expermienting with variable components over here: fonttools/fonttools#2302, I can gladly make a non-experimental PR for fonttools for PaintScale.

I'd like to get some clearance about which variants of PaintScale are desired at this point. All 8 like @behdad suggested, or a smaller set, more in line with the current PaintRotate, PaintSkew paints? Or should PaintRotate and PaintSkew grow centerless variants?

**Comment by rsheeter** [comment]
Let's tentatively add them all.

**Comment by justvanrossum** [comment]
> Let's tentatively add them all.

Including center-less version for PaintRotate and PaintSkew?

If yes, are the names in my [comment above](https://github.com/googlefonts/colr-gradients-spec/issues/279#issuecomment-830549924) as you'd like them to be? `PaintRotate` would become `PaintRotateCenter`, and the `PaintRotate` would not have a center, so we'd have both name and format changes.

**Comment by behdad** [comment]
Alternative name for `PaintRotateCenter`: `PaintRotateAround`.

**Comment by justvanrossum** [comment]
`PaintRotateAtCenter`? `PaintRotateWithCenter`? "Around" is nice for Rotate, but less so for Skew and Scale.

**Comment by justvanrossum** [comment]
Thinking further in terms of a bit field: an alternative idea is to combine all "decomposed" transform paints into one, and have format bits for:
- have translation
- have rotation
- have skew
- have scale
- have center

This gives a more uniform yet more flexible set of possibilities, and allows for more a compact representation in some cases (rotate and scale having the same center is a case I'm looking at in our (Robo)CJK dataset).

The disadvantage is that it needs a single defined order in which the transformations should be applied. Should one need to deviate from that order, multiple paints will be needed after all.

FWIW, in RoboCJK, the affine matrix is calculated from translation, rotation, skew, scale and center like this:
```python
    t = Transform()
    t = t.translate(x + tcenterx, y + tcentery)
    t = t.rotate(math.radians(rotation))
    t = t.scale(scalex, scaley)
    t = t.skew(math.radians(skewx), math.radians(skewy))
    t = t.translate(-tcenterx, -tcentery)
```
(We don't really use skew — perhaps it would be more logical to do it between rotate and scale.)

**Comment by behdad** [comment]
> `PaintRotateAtCenter`? `PaintRotateWithCenter`? "Around" is nice for Rotate, but less so for Skew and Scale.

Why not? Skew around center; scale around center..

**Comment by behdad** [comment]
> Thinking further in terms of a bit field: an alternative idea is to combine all "decomposed" transform paints into one, and have format bits for:

That's also what I suggested to Rod et al shortly after meeting with you. And I like to design something like that for extended components in the glyf table as well, so would be nice if they match. But that might be too late for this proposal.

I'm still interested to iron the details out though. A few points:

* Skew and Scale commutate I think. No?
* I still think skew-by-angle is wrong and should be removed,
* I suggest we add support all four of: no-translate, pre-translate, post-translate, translate-sandwich (aka centered).

**Comment by justvanrossum** [comment]
> Skew and Scale commutate I think. No?

Only for a uniform scale. Same with rotate.

**Comment by PeterConstable** [comment]
I've made an initial commit in #290 with additions to the C++ header structs. After there's consensus on that, I'll make changes to the OFF AM2 draft page.

**Comment by PeterConstable** [comment]
PR #290 now has a complete draft of changes to add PaintScale etc. as discussed here.

**Comment by rsheeter** [comment]
How do we feel about "origin" vs "center"? - e.g. PaintSkew is relative to the default origin, PaintSkewOrigin (or soemthing along those lines) is a skew with a custom origin.

**Comment by PeterConstable** [comment]
I think that would be confusing. Even "custom origin" is likely to lead to confusion.

**Comment by PeterConstable** [comment]
#290 merged; closing.
