### ISSUE TITLE
Well-formedness definition must prohibit self-referential PaintColrGlyph 

### ISSUE THREAD

**Issue by drott** [googlefonts/colr-gradients-spec#282]
It seems it's possible to build a cycle by having `PaintColrGlyph` refer back to the current glyph being drawn, directly or indirectly. The well-formedness/validity section needs to prohibit that and a set similar to the visited Paints needs to be kept in order not to revisit a previous glyph id in the same branch.

**Comment by rsheeter** [comment]
Maybe I'm misunderstanding but from a glance at "5.7.11.1.9 Color glyphs as a directed acyclic graph" I'm expecting this would be detected as you would encounter a Paint you've seen before and detect the cycle?

**Comment by rsheeter** [comment]
Per f2f closing
