### ISSUE TITLE
Contemplate reduction of indirection

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#283]
@behdad was wondering about a model where we reduce indirection; we may have considerable use of offsets that are unnecessary. Would like to count by paint type and ideally seek chains where the offset is pointless (the paint could just follow inline).

**Comment by PeterConstable** [comment]
I assume size-savings (avoid an Offset32) isn't the concern. (I don't think we'd want to define a parallel pairs of offset-less formats.) We could specify that an offset of 0 means that the paint subtable immediately follows the current paint table.

Is this really a v1 issue?

**Comment by behdad** [comment]
Wrong assumption.

**Comment by PeterConstable** [comment]
We're up to 32 paint formats now (after adding PaintScale etc.). Formats 1 to 9 (solid, gradients) and 11 (PaintColrGlyph) don't have a fields for paint subtable offsets. The formats that do are:
* PaintGlyph (format 10)
* transforms (formats 12 to 31)
* PaintComposite (format 32) — has two offset fields.

We already doubled the transform formats to have var/no-var pairs. And we've doubled some further for center/no-center pairs. We'd be adding 20 more transform formats.

The gradient formats also have offsets to ColorLine subtables. Doubling those would be six more formats.

A potential concern is the precedent: how far do we go in future OT enhancements creating variants of formats for different combinations of optional fields?

**Comment by rsheeter** [comment]
Size savings _may_ be a concern. I aspire to measure but I haven't had time to actually do it yet. Too many priorities lol.

I think we should let the data speak, if it saves 1% (of the overall font) we can forget this. If it saves a significant amount maybe it's worth thinking about how we might support no-offset variations. We could invest a format bit, we could say referenced paints *always* follow except when a special format (jump, PaintOffset as it were) is found, ... I'm sure there are other options.

Wrt number of formats I think it's important to remember that an implementation isn't obliged to define structures per format. One could very reasonably unpack every many transform formats into the same structure. One could unpack SomethingNotVariable and SomethingVariable into the same struct, etc. A compiler might have to care about all variants but that's fine, more flexibility to the compiler is a good thing.

**Comment by rsheeter** [comment]
Not quite ready to close but so far my experiments are making this appear unappealing.

**Comment by behdad** [comment]
I would have encouraged doing this for Translate at least *if* there was no further technical issue. But if we do it as is, the base of the offsets in subsequent Paint's become unclear. That's a pain.

**Comment by PeterConstable** [comment]
I'm not opposed to considering this if it would provide useful benefit. Re this, however,

>the base of the offsets in subsequent Paint's become unclear

the spec clearly states at the beginning of the section on the formats (5.7.11.2 in OFF),

>All table offsets are from the start of the parent table in which the offset is given, unless otherwise indicated.

So, with current formats, the offset given in any paint table is relative to the start of that paint table. And if we were to add formats for which the linked child table immediately follows the parent, then any offset in that child table would be relative to the start of that child table. Thus, I don't see anything that isn't clear.

**Comment by behdad** [comment]
> the spec clearly states at the beginning of the section on the formats (5.7.11.2 in OFF),
> 
> > All table offsets are from the start of the parent table in which the offset is given, unless otherwise indicated.
> 
> So, with current formats, the offset given in any paint table is relative to the start of that paint table. And if we were to add formats for which the linked child table immediately follows the parent, then any offset in that child table would be relative to the start of that child table. Thus, I don't see anything that isn't clear.

What is a table? Anything we call a table becomes a table? What happens when a table includes other tables inline?

**Comment by PeterConstable** [comment]
Currently (IIRC), tables are always called "tables", are always referenced via an offset, and don't occur inline within another table—if it's within another table and there's reason to treat it as a sub-structure (rather than just having the members be members of the parent table), then that would be called a record.

Having a table with a child sub_table_ immediately follow would deviate a bit from that model in that an offset field wasn't used to locate the child. I don't recall any counter-example offhand but wouldn't be too surprised if there is already some existing case like that. You could maintain a principle of "tables are referenced by offset" by saying that it was still referenced by offset, but the offset was given implicitly, as the size of the parent table.

**Comment by behdad** [comment]
> Having a table with a child sub_table_ immediately follow would deviate a bit from that model in that an offset field wasn't used to locate the child.

Hence my point.

> I don't recall any counter-example offhand but wouldn't be too surprised if there is already some existing case like that.

I don't know of any.

> You could maintain a principle of "tables are referenced by offset" by saying that it was still referenced by offset, but the offset was given implicitly, as the size of the parent table.

That's just word-play. Implementations need to change to accommodate this new style.. which.. again.. would not have been a problem if we had adopted self-contained offsets. I still encourage doing that.

**Comment by PeterConstable** [comment]
It's unclear what "self-contained offset" means: sounds like "the referenced structure contains its own offset", but that wouldn't make sense. Please clarify.

**Comment by behdad** [comment]
> It's unclear what "self-contained offset" means

Offsets that are relative to the start address of the offset field itself. "self-contained" as in not needing any external "base" information to resolve.

https://github.com/googlefonts/colr-gradients-spec/issues/11#issuecomment-645725188

**Comment by rsheeter** [comment]
If we start introducing offset-less (children follow immediately) Paints - and I currently expect we will want to - I'm +1 on self-contained offsets. I wasn't enthused when they didn't seem to solve a problem but now they do.

**Comment by rsheeter** [comment]
So far, amusingly, I've seen bigger wins from *adding* offsets (an array of offset to coordinate is a huge win for #277 in testing) than removing them. As we're low on time for V1 I suggest we close this for now. If we uncover places where this is a big win we can add offset-free paints in v2.

**Comment by behdad** [comment]
Sgtm. Thanks for experimenting!
