### ISSUE TITLE
Question about VarF2Dot14, 16-bit deltas, and overflow

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/colr-gradients-spec#284]
Do I understand correctly that the delta's stored in the VarStore for VarF2Dot14 are also 16 bit values?

During our `VarC` work, we encountered problems with overflows: even if all master values are limited to a [0.0, 1.0] range, the delta values may go outside of this range easily. An example:

```python
>>> from fontTools.varLib.models import VariationModel
>>> locations = [{}, {"a": 1}, {"b": 1}, {"a": 1, "b": 1}]
>>> model = VariationModel(locations)
>>> masterValues = [0, 1, 1, 0]
>>> model.getDeltas(masterValues)
[0, 1.0, 1.0, -2.0]
```
Now, -2.0 is just touching the edge of the F2DOT14 range, but the theoretical min/max range of delta values increases with the number of master positions, and can easily reach values that do not fit into F2DOT14. This is a big problem, so I hope I'm missing something.

@behdad?

**Comment by behdad** [comment]
There is no such requirement whatsoever. All is good.

**Comment by behdad** [comment]
> Do I understand correctly that the delta's stored in the VarStore for VarF2Dot14 are also 16 bit values?

For context, I noticed that PeterC has slipped in wording to that effect when writing down the 32bit VarStore details. The additional restriction was done without consulting with anyone else, and I asked Rod and it was reverted.

**Comment by behdad** [comment]
Same story about overflows and whatnot...

**Comment by justvanrossum** [comment]
Thanks, I was hoping as much (since you talked about it during our call), but didn't fully understand.

Still not 100% confident I understand the mechanics: it is possible for a VarF2DOT14 to either have 16 or 32-bit delta entries in VarStore, depending on what the designer or compiler deems necessary? If so, how does a rendering client know which one it is?

**Comment by behdad** [comment]
> Still not 100% confident I understand the mechanics: it is possible for a VarF2DOT14 to either have 16 or 32-bit delta entries in VarStore, depending on what the designer or compiler deems necessary?

Correct.

> If so, how does a rendering client know which one it is?

There is no ambiguity. VarStore has this API: you give it a 32bit "Variation Index" number and designspace coordinates, it returns a numerical value (delta). What you do with that or what you add it to is irrelevant to the variation store.

**Comment by behdad** [comment]
Ie. the VariationStore is self-contained. There is no separate 16bit VarStore and 32bit VarStore.

**Comment by justvanrossum** [comment]
> it returns a numerical value (delta)

I think I'm slowly getting it. Is the following correct:

So for F2DOT14 we're simply receiving an int, and we treat the 14 least significant bits as the fractional part. Internally VarStore may have stored it as a 16 bit value if the delta needed 2 integer bits or fewer, but as a 32 bit value if more than 2 int bits were needed.

(Sorry for being so dense.)

**Comment by justvanrossum** [comment]
Thanks so much for the clarification. It's so obvious once you get it...

**Comment by davelab6** [comment]
@justvanrossum Does the spec text need an edit to clarify this so that you wouldn't stumble over this aspect if you were reading it from scratch?

**Comment by davelab6** [comment]
@justvanrossum Does the spec text need an edit to clarify this so that you wouldn't stumble over this aspect if you were reading it from scratch?

**Comment by justvanrossum** [comment]
Perhaps an extension of this section:

> In general, variation deltas are (logically) signed 16-bit integers, and in most cases, they are applied to signed 16-bit values (FWORDs) or unsigned 16-bit values (UFWORDs). When scaled deltas are applied to F2DOT14 values, the F2DOT14 value is treated like a 16-bit integer. (In this sense, the delta and the F2DOT14 value can be viewed as integer values in units of 1/16384ths.)

> If the context in which the VarF2Dot14 is used constrains the valid range for the default value, then any variations by applying deltas are clipped to that range.

It could point out that while final values may be limited to a range (such as [0, 1], the deltas (and therefore intermediate calculation values) may well be outside of that range, and that all is fine as long as deltas fit in 32 bits.
