### ISSUE TITLE
Replace PaintColorLayers occurences with correct PaintColrLayers term

### ISSUE THREAD

**Issue by drott** [googlefonts/colr-gradients-spec#285]
We have a couple of occurences of `PaintColorLayers` which should be PaintColrLayers.

**Comment by vlevantovsky** [comment]
> We have a couple of occurences of PaintColorLayers which should be PaintColrLayers.
Thank you, this was fixed in the ISO amendment text but I forgot to mention it here.

**Comment by drott** [comment]
> Why are we using the abbreviated form "Colr" here?

We are using the `PaintColrLayers` table term/name to describe a Paint table structure that is part of the COLR table.

**Comment by vlevantovsky** [comment]
> Why are we using the abbreviated form "Colr" here?

My understanding is that COLR as a table name is not an abbreviation for "color", it's for "Composition Of LayeRs".
