### ISSUE TITLE
With variability, pre-computing a bounding box is non-trivial

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/colr-gradients-spec#289]
I'm not sure what I'm asking here, but I'd like to raise awareness that pre-calculating a (variable) bounding box for a variable color glyph (to put in glyf+gvar or CFF2, as required by the spec) is non-trivial.

Not only that, but the tightest possible bounding box may not be expressible without higher order interpolation.

But even calculating a non-tight bounding box that is guaranteed to always be large enough is non-trivial, for example in the case of a rotating element using PaintRotate.

The burden for authoring tools to get this right is pretty heavy, if you ask me.

Am I overthinking this? Does anyone have ideas of how to even approach this in a general way?

**Comment by rsheeter** [comment]
I believe you are right that it's difficult and indeed we don't even do it right for static in our current implementation. However, I'm not (yet) convinced it's infeasible. My instinct is to say "leave it to the compiler" and the compiler can evolve independent of the spec.

https://github.com/googlefonts/nanoemoji/issues/238
https://github.com/googlefonts/nanoemoji/issues/239

**Comment by PeterConstable** [comment]
Not sure there's any alternative.

**Comment by rsheeter** [comment]
I think the right thing to do is close here - no spec change anticipated - and pursue further in the context of the public compiler (tickets above). Please reopen if you disagree.

**Comment by justvanrossum** [comment]
I agree, sorry for not closing sooner.

**Comment by drott** [comment]
Commenting here as well after Rod closed https://github.com/googlefonts/nanoemoji/issues/238#issuecomment-912049713 The new changes in the spec for explicit ClipBox or not specifying a ClipBox provide a solution for it. Precomputing and adding a ClipBox can be a useful optimisation. For variable scenarios, not specifying a ClipBox is an option in which case the rasteriser traverses the graph to determine a bounding box.
