### ISSUE TITLE
clarify offset in BaseGlyphV1Record

### ISSUE THREAD

**Issue by qxliu76** [googlefonts/colr-gradients-spec#293]
5.7.11.2.3 BaseGlyphV1List and LayerV1List
Offsets in LayerV1List are from the beginning of LayerV1List, but not sure about offsets in BaseGlyphV1Record.

The spec should clarify whether the offset in BaseGlyphV1Record is from the beginning of BaseGlyphV1Record or from the beginning of BaseGlyphV1List?

**Comment by PeterConstable** [comment]
See the beginning of 5.7.11.2:

>All table offsets are from the start of the parent table in which the offset is given, unless otherwise indicated.

This is a general convention throughout the OT spec.
