### ISSUE TITLE
Remove "V1" from member names

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#299]
Back in #14, there was discussion about removing "V1" from field names, and seems like there was some agreement with removing (see [comment](https://github.com/googlefonts/colr-gradients-spec/issues/14#issuecomment-672993399) and following comments). But that seems to have gotten lost.

In the COLR v1 table, should these field names be revised?
- baseGlyphV1ListOffset -> baseGlyphListOffset
- layersV1Offset -> layerListOffset

And should these struct names be revised?
- BaseGlyphV1List table -> BaseGlyphList table
- LayerV1List table -> LayerList table

**Comment by rsheeter** [comment]
I believe this is now resolved, please reopen if I am mistaken
