### ISSUE TITLE
Single extend, or separate start/end extend?

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#30]
PDF allows for extend behaviour to be defined separately for the start and end of a colour line. Should we extend the proposal to allow for that?

See discussion in <The OT spec doesn't define how variation deltas can be applied to items that are F2Dot14. See discussion in <https://github.com/PeterConstable/OT_Drafts/blob/master/COLR_V1/COLRv1_OpenIssues.md#extending>.

**Comment by rsheeter** [comment]
For COLRv1 we're trying hard to specify things graphic libraries already support; for this reason we gave only one extend.

**Comment by PeterConstable** [comment]
Well, if PDF allows for separate start/end extend flags, then clearly _some_ libraries support it. We should be careful about allowing certain existing libraries preferentially limit the design: it's much, much easier to add functionality when the format is first being specified than to add it later on.

In this case, a designer could work around the limitation with additional paint layers, so probably not critical.
