### ISSUE TITLE
Clarify composite 'glyf' has to refer to other 'glyf' items?

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#303]
@garretrieger was asking about whether a composite glyf can refer to a COLRv1 glyph. I have always understood composite glyf to be required to be another glyf. https://docs.microsoft.com/en-us/typography/opentype/spec/glyf#composite-glyph-description doesn't appear to directly say that. My guess is the assumption was there would be no other possibility when it was written. 

Perhaps it should?

**Comment by behdad** [comment]
There's indeed a "pecking" order implied: GSUB is processed, then COLR, then glyf (composites).

**Comment by PeterConstable** [comment]
Glyph entries in 'glyf' can't reference glyph descriptions in COLR (or in CFF, CFF2...). Similarly, glyph entries in CFF can't reference, etc., etc.

I don't think this needs to be called out in the COLR chapter. Clarification for 'glyf' could be added there, but I suggest @garretrieger submit an issue for this using the feedback mechanism on the [OT glyf page](https://docs.microsoft.com/en-us/typography/opentype/spec/glyf).

**Comment by rsheeter** [comment]
Unmarking for COLRv1

**Comment by rsheeter** [comment]
Actually I think it makes sense to close here and file on OT
