### ISSUE TITLE
Can rotation center use FWORD?

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#308]
Ref discussion on https://github.com/googlefonts/colr-gradients-spec/pull/307. Tl;dr pro: saves bytes. con: targeting a non-int center becomes more complex and likely costs additional bytes.

EDIT: corrected description of downside, initial text was too strong

**Comment by anthrotype** [comment]
+1 on using FWORD

> target the actual center.

one can always increase the units per em

**Comment by anthrotype** [comment]
FWIW also the centerX/centerY of PaintSweepGradient is an FWORD (signed int16)

**Comment by rsheeter** [comment]
@lorp curious how you see @anthrotype suggestions? - I confess to leaning toward FWORD. Note that you can also chain Paint's to achieve certain effects (e.g. shift, scale around center, shift).

**Comment by PeterConstable** [comment]
@rsheeter Did you do analysis that can inform what the likely benefit wrt size savings might be?

Doubling UPEM just to handle centers might not be desirable, but I wouldn't think it would be too problematic to use PaintTransform instead when needed.

**Comment by rsheeter** [comment]
In our heavily componentized (via COLR) test font (which, annoyingly for this purpose is not public) this change is a significant win, upgrading to the reduced precision form is almost always safely (as in the center is an int and the rotation fits into F2Dot14) possible.

**Comment by rsheeter** [comment]
I believe that means that this change makes what we expect to be the normal use case cheaper, makes center coordinates consistent over COLRv1, and while it complicates rotation around a high precision center it doesn't make it impossible.

**Comment by PeterConstable** [comment]
Seems like a good compromise to get better efficiency for high-use cases while having alternatives available when needed (PaintTransform, or a combination of transforms—e.g., scale or translate before and after the rotation).

**Comment by Lorp** [comment]
I’m still against this, on the grounds that we’re treating fonts as second-class to CAD or general computer graphics, where this kind of extreme economy is unacceptable.

The best and simplest remedy is to spec a high precision rotation transform as an alternative.

Better than what is proposed would be to store 2x the coordinates. Thus for a centre at (50.5, 50.5) we store (101,101). This provides a range of [-16384,16383] FUnits for rotation centre coordinates (in 0.5 steps), which is sufficient. I think this special handling of an FWORD is justified by the nature of this common use case of rotation about glyph centre. (@anthrotype, is this what you are talking about, or are you talking about doubling upem for the entire font??)

The PaintTransform alternatives simply do not work for variable rotation. Consider a contour that measures 100x19 FUnits rotated about its centre from 0° to 180°. The designer has the reasonable expectation that the 180° form will align exactly with the 0° form. This is not the case currently, and therefore makes me consider the current proposal broken.

**Comment by anthrotype** [comment]
you can chain a PaintTransform (with Fixed precision floats) that translates the origin to where you want the center of rotation to be (at 0.5 or whatever fractional units), followed by the PaintRotate, in turn followed by another PaintTransform that undoes the initial translation

**Comment by Lorp** [comment]
Indeed, that works and doesn’t remove semantics… makes me think it would be simpler if rotations were always around the origin :)

**Comment by PeterConstable** [comment]
If there are a lot of occurrences in fonts using the revised formats, then I think the size savings would be worthwhile. (Btw, CAD files don't get distributed the way that font files do, so size isn't the same concern.)

But if it turned out that a lot of fonts might benefit from a rotate paint that supported higher precision center coords (or a higher-precision scale or translate), to have smaller size than a chain of transforms, that could be added in the future.

**Comment by rsheeter** [comment]
> second-class to CAD or general computer graphics

I think I would argue fonts aren't "second-class," they are solving a different problem with significantly different constraints.

**Comment by Lorp** [comment]
Given @anthrotype’s reminder about pre- and post-rotation translates, I no longer consider the current proposal broken, and I withdraw my previous objection. I would simply request that a note about this is given in the spec for PaintRotate, to help implementors with accurate rotation-about-centre.

**Comment by Lorp** [comment]
Thanks Peter, LGTM.
