### ISSUE TITLE
static item values when ItemVariationStore is present

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#31]
In the proposal for COLR v1, all new values can be variable. But a font might want some items to be variable yet others static. The proposal doesn't indicate how to have static values if an ItemVariationStore is present.

See <https://github.com/PeterConstable/OT_Drafts/blob/master/COLR_V1/COLRv1_OpenIssues.md#static-values-when-an-item-variation-store-is-present> for details.

**Comment by behdad** [comment]
Static values have no variation. No-variation is encoded efficiently-enough in ItemVariationStore already. Basically one VarIdx will get allocated to "no variation" by the compiler.

I know I proposed in the 2019 Seattle meeting that `oxFFFFFFFF` variation-index (ie. major=0xFFFF,minor=0xFFFF in the way OT spec'ed ItemVariationStore) be spec'ed to mean "no variation". Everyone (including Greg) agreed with that but never got into spec because no one knew how to get *anything* into the spec.

**Comment by behdad** [comment]
From https://docs.google.com/document/d/1fV___desnqeofSejfbyovJ_hWmYeaem7n4nhIJPwl6U/edit

"""
No-variation VarIdx [behdad]
Make 0xFFFF outer/inner values legal for no-variation?  Note that 0xFFFF is an unused value for both outer and inner.  Note that this cannot be used in HVAR, etc, when a mapping is involved.  This will be useful in COLR gradients proposal and possibly other places in future, but also not a huge deal one way or another.

=> Resolution: accepted.  behdad to codify.
"""

behdad to codify ***how***? For months I asked Greg to meet with me to figure out a way that people outside MS / Peter can have access to OpenType spec sources. He refused to meet with me about that or do anything.

**Comment by PeterConstable** [comment]
It should be possible to incorporate this into the OT spec or OFF whenever COLR v1 is added. It just needs clear statements about what should be stated where --- in the variations common formats chapter? in the COLR chapter? in the HVAR chapter? elsewhere? If we think it would be useful, we can do the right thing as part of COLR v1.

**Comment by behdad** [comment]
In the ItemVariationStore part of the spec say major=0xFFFF,min=0xFFFF means "no variation".

Make sure you do NOT make it illegal for compilers to continue encoding "no variation" in other ways!

**Comment by behdad** [comment]
> In the ItemVariationStore part of the spec say major=0xFFFF,min=0xFFFF means "no variation".

Let's make sure this happens.

**Comment by PeterConstable** [comment]
I was considering NULL offset as a way to get the required indication of "no variation". But I wasn't aware of (or had forgotten) the discussion at the 2019 meeting. Since it appears there was consensus to use FFFF/FFFF to indicate "no variation" we could certainly go with that.

Was there a reason why FFFF/FFFF was chosen for this purpose rather than `<any I>`/`<any J>` where `itemVariationDataOffsets[I] == 0`? (Wouldn't that achieve the desired effect?)

**Comment by PeterConstable** [comment]
@behdad : If itemVariationDataOffsets[i] == 0 means no variation data, does specifying `major=0xFFFF,min=0xFFFF means "no variation"` result in two different ways to achieve the same thing?

**Comment by behdad** [comment]
> @behdad : If itemVariationDataOffsets[i] == 0 means no variation data, does specifying `major=0xFFFF,min=0xFFFF means "no variation"` result in two different ways to achieve the same thing?


A compiler is allowed to encode as many "no-variation" items as they want. What you are suggesting doesn't make sense to me. A NULL offset then needs to be used by some minor number. Any minor number will be out-of-range.  So, no they are not the same. Just follow the summer agreement.

**Comment by PeterConstable** [comment]
A strong reason not to use `itemVariationDataOffsets[I] == 0` is that it requires a lookup into that array to determine there is no variation, whereas FFFF/FFFF indicates that directly in the indices. So we should go with that.

**Comment by PeterCon** [comment]
Changes incorporated into draft of OT spec next version.
