### ISSUE TITLE
use ColorIndex or VarColorIndex in VarColorStop?

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#318]
In VarColorStop, a varIndexBase member is needed for the stopOffset. Should that base also be used for the embedded alpha? That is, should VarColorStop have ColorStop as a member, with VarColorStop.varIndexBase also applied to VarColorStop.color.alpha?

Or, should VarColorStop have a VarColorStop member, with VarColorStop.varIndexBase used only for VarColorStop.stopOffset, and separately have VarColorStop.color.varIndexBase used for VarColorStop.color.alpha? (So, two separate varIndexBase members in the two structs, each used for exactly one member.)

(Similar question for PaintVarSolid: if it had a varIndexBase member that applied to its color.alpha, then perhaps VarColorIndex wouldn't be needed at all.)

**Comment by rsheeter** [comment]
Per f2f I'm tempted to suggest dropping ColorIndex completely, just list the fields.

**Comment by rsheeter** [comment]
Fixed by #320
