### ISSUE TITLE
Update DeltaSetIndexMap to beyond 16bit

### ISSUE THREAD

**Issue by behdad** [googlefonts/colr-gradients-spec#319]
Currently `DeltaSetIndexMap` is limited to 16bit entries:

https://docs.microsoft.com/en-us/typography/opentype/spec/hvar

Type | Name | Description
-- | -- | --
uint16 | entryFormat | A packed field that describes the compressed representation of delta-set indices. See details below.
uint16 | mapCount | The number of mapping entries.
uint8 | mapData[variable] | The delta-set index mapping data. See details below.

The `entryFormat` has lots of reserved bits:

Mask | Name | Description
-- | -- | --
0x000F | INNER_INDEX_BIT_COUNT_MASK | Mask for the low 4 bits, which give the count of bits minus one that are used in each entry for the inner-level index.
0x0030 | MAP_ENTRY_SIZE_MASK | Mask for bits that indicate the size in bytes minus one of each entry.
0xFFC0 | Reserved | Reserved for future use — set to 0.

We should use one to add a 32bit variation. To keep it backwards compatible, the 32bit extension should append more data at the end of the current 16bit array. That also enables us to rethink different encoding options, if desirable. For example, a 20bit mode.

I'm thinking about this now.

**Comment by PeterConstable** [comment]
>Currently DeltaSetIndexMap is limited to 16bit entries...
> We should use one to add a 32bit variation...

Please clarify: Do you meant to allow the number of (logical) mapping entries to be >65535?


> To keep it backwards compatible, the 32bit extension should append more data at the end of the current 16bit array.

So, you would keep mapCount as uint16? How would the higher count be represented? 

And is back compat really a problem for this structure? (Existing implementations use it only in HVAR and VVAR, and as long as glyph IDs remain 16-bit there would not be any need in HVAR or VVAR for more than 65535 entries. In COLR, any implementations would be new.) Why not add a flag in entryFormat that determines whether mapCount is uint16 or uint32?

**Comment by behdad** [comment]
> Please clarify: Do you meant to allow the number of (logical) mapping entries to be >65535?

Yes.

> And is back compat really a problem for this structure? (Existing implementations use it only in HVAR and VVAR, and as long as glyph IDs remain 16-bit there would not be any need in HVAR or VVAR for more than 65535 entries. In COLR, any implementations would be new.)

That's a *very* good point. Let's do that.

> Why not add a flag in entryFormat that determines whether mapCount is uint16 or uint32?

Let's rename the top byte of `entryFormat` to just `format`. Format 0 would be the existing struct. We'll add format 1 which has `uint32` mapCount.

Any input on 20bit format?

**Comment by rsheeter** [comment]
> Any input on 20bit format?

Naively I think I might have expected 24? Was there a reason 20 was particularly desired?

**Comment by PeterConstable** [comment]
For fields / subtable offsets that are repeated many times, it can be worth using a 24-bit type. But for fields that occur once, I don't think there's a particular advantage of using 24-bit vs. 32-bit.

**Comment by PeterConstable** [comment]
>Let's rename the top byte of entryFormat to just format. Format 0 would be the existing struct. We'll add format 1 which has uint32 mapCount.

So divide the current uint16 entryFormat field into two separate uint8 fields, like so?

*DeltaSetIndexMap format 0:*
Type | Name | Description
-- | -- | --
uint8 | format | DeltaSetIndexMap format: set to 0.
uint8 | entryFormat | A packed field that describes the compressed representation of delta-set indices. See details below.
uint16 | mapCount | The number of mapping entries.
uint8 | mapData[variable] | The delta-set index mapping data. See details below.

*DeltaSetIndexMap format 1:*
Type | Name | Description
-- | -- | --
uint8 | format | DeltaSetIndexMap format: set to 1.
uint8 | entryFormat | A packed field that describes the compressed representation of delta-set indices. See details below.
uint32 | mapCount | The number of mapping entries.
uint8 | mapData[variable] | The delta-set index mapping data. See details below.

**Comment by rsheeter** [comment]
Wrt 20 vs 24 bits I believe this was in reference to size of each entry (packed format that uses one, two, three or four bytes) so high enough repetition to care. Currently sized in bytes so 24 is already achievable. We can already land at 8,16,24,32 so even devoting 1 more bit to mean "+4 bits, up to a max of 32" could suffice to let us access 12, 20, 28 bit entries.

**Comment by PeterConstable** [comment]
But what existing problem is needing to be solved by allowing 12, 20...?

**Comment by rsheeter** [comment]
Actually a bit for -4 is better, then you can use 4 and you can't land out of range (on 36).

A DeltaSetIndexMap for a large set of deltas can be quite large so allowing the compiler to choose just enough space is desirable.

**Comment by PeterConstable** [comment]
Indexing into delta sets in an ItemVariationStore involves 32 bits for a two-level organization: 16 bits ("outer" index) to select an ItemVariationData subtable, and 16 bits ("inner" index) to select a DeltaSet record from the deltaSets[] array. The proposal is not about that.

In the DeltaSetIndexMap, each entry packs together the values for the "outer" and "inner" index components. It's the total size of each entry that is 1, 2, 3 or 4 bytes (8, 16, 24 or 32 bits). But for a given entry size, the bits can be divided into "outer" and "inner" parts in any way. E.g., for 16-bit entries, you can have 1 bit for outer and 15 bits for inner; or 2 bits for outer and 13 bits for inner; and so on.

So, the question is whether there is data indicating that we have significant inefficiencies because we can't have entries that are 12 bits (for outer/inner data of 1/11, 2/10, 3/9...), or 20 bits (4/16, 5/15, 6/14...) or 28 bits (12/16, 13/15, 14/14...).

Note that this is orthogonal to the matter of whether the DeltaSetIndexMap in COLR might require more than 65536 entries.

**Comment by behdad** [comment]
After further though, I'm retracting the 4bit proposal. Two reasons:

- Without the 4bit extension, ie. just adding 32bit mapCount, then a compiler can continue to produce the most optimized format and be guaranteed that for fonts that can be represented in OpenType 1.8 (ie. 64k glyph limit), the produced DeltaSetIndexMap is legal in OT1.8. If we introduced more compact encoding using 4bit extension, a compiler would need to be instructed of what "profile" to adhere to.

- I also am justified it's misguided to try to save 4bits per entry here, whereas if we wanted to go to bit tweedling, adding more compact encoding to ItemVariationStore would be more justified; and we already touched that structure anyway.

As such, and I suggest we just go for a 32bit expansion.

**Comment by behdad** [comment]
> > 
> 
> So divide the current uint16 entryFormat field into two separate uint8 fields, like so?
> 
> _DeltaSetIndexMap format 0:_
> 
> Type	Name	Description
> uint8	format	DeltaSetIndexMap format: set to 0.
> uint8	entryFormat	A packed field that describes the compressed representation of delta-set indices. See details below.
> uint16	mapCount	The number of mapping entries.
> uint8	mapData[variable]	The delta-set index mapping data. See details below.
> _DeltaSetIndexMap format 1:_
> 
> Type	Name	Description
> uint8	format	DeltaSetIndexMap format: set to 1.
> uint8	entryFormat	A packed field that describes the compressed representation of delta-set indices. See details below.
> uint32	mapCount	The number of mapping entries.
> uint8	mapData[variable]	The delta-set index mapping data. See details below.

This looks good to me. Thank you.

**Comment by rsheeter** [comment]
Given @PeterConstable landed #328 I believe this is done.
