### ISSUE TITLE
PaintRotate range concerns

### ISSUE THREAD

**Issue by Lorp** [googlefonts/colr-gradients-spec#332]
I’m concerned that F2DOT14, 2 bytes, for rotation angle (rather than F16DOT16, 4 bytes) compromises the usefulness of _PaintRotate_ in variable fonts, bearing in mind that the principal use case of _PaintRotate_ is rotation variation.

F2DOT14 has a range of [-2, 2). Thus with the 180° multiplier, _PaintRotate_ handles [-360°,360°). However it strikes me as very useful to offer the following possibilities to font makers, neither of which is currently possible:

* offer a rotation range of 0° to 360° (we must use -360° to 0° or -180° to 180°)
* offer multiple rotations of a component with a range from, say, 0° to 2880° (8 rotations), e.g. the gears in a settings symbol, or the wheels of a vehicle emoji

Thoughts?

**Comment by rsheeter** [comment]
Think of the F2Dot14 as setting the initial rotation. The variable part isn't f2dot14 and shouldn't be constrained to that range. I would expect all the examples to be possible in this way. Could be we need a wording tweak to make that moe explicit.

**Comment by Lorp** [comment]
Ah, thanks for the correction!

**Comment by PeterConstable** [comment]
Fixed by #334. Similar wording changes were also made for PaintSkew in #338.
