### ISSUE TITLE
Distinguish ItemVariationStore formats (add format 1) due to change to wordDeltaCount field

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#339]
@anthrotype suggested that the change in ItemVariationData of treating the wordDeltaCount field as a packed field with a new meaning assigned to the high-order bit should result in a format bump to ItemVariationStore.

It does seem that should be done:

Currently, the high-order bit of wordDeltaCount should never be set since no existing font would define that many regions (which are roughly proportional to design masters), and in OT 1.8.4 the VariationRegionList.regionCount field was restricted to <32K. That entails that the number of logical entries in each delta set must be <32K. But it probably isn't safe to assume that implementations would validate the ItemVariationData.wordDeltaCount field is, accordingly, <32K.

If existing implementations read a format 0 ItemVariationStore in which the high-order bit of wordDeltaCount is set, they may assume there are >32K in16 entries in each delta set. That would likely result in wrong interpretation of the data, but could also result in read overrun past the end of the ItemVariationStore (and potential security vulnerability).

Separate formats 0 and 1 can be defined: they would have the same fields, but in format 0 the LONG_WORDS flag is not used.

**Comment by anthrotype** [comment]
the current format is 1 so the proposed new format would be format 2

https://docs.microsoft.com/en-us/typography/opentype/spec/otvarcommonformats#item-variation-store-header-and-item-variation-data-subtables

**Comment by justvanrossum** [comment]
> Separate formats 0 and 1 can be defined: they would have the same fields, but in format 0 the LONG_WORDS flag is not used.

This feels a bit redundant: couldn't the new format be for "long words" only, and the old format for "short words" only?

**Comment by anthrotype** [comment]
the `wordDeltaCount` field (whose high bit becomes the LONG_WORDS flag) is defined on the ItemVariationData subtable, not on the parent ItemVariationStore table, where the Format field is specified. A Format 2 VarStore can contain a mix of VarData subtables, some of which use shorts, other use longs, depending on the LONG_WORDS flag. A compiler would use format 2 whenever there's any VarData subtable that contains long deltas, or the current format 1 when none do.

**Comment by justvanrossum** [comment]
Ah, somehow I missed that completely. Sorry for the noise.

**Comment by anthrotype** [comment]
a Format 2 VarStore containing no "long" VarData is arguably useless but still valid

**Comment by behdad** [comment]
No.

**Comment by PeterConstable** [comment]
> No.

@behdad Please clarify: What are your responding to?

**Comment by rsheeter** [comment]
Adding formats comes at implementation cost so it's best to default to not doing so where we don't have to. Here it seems perhaps we don't have to.

This change was, sinces it's conception, argued to be safe, no need to change format. Per f2f w/@behdad I believe the argument is that word count has to be less than region count and a legacy parser will see a bad relationship between those fields and stop.

On that basis I'm inclined to suggest we close w/o making changes.

**Comment by PeterConstable** [comment]
We already had wording, `the number of deltas that use the long ("word") representation... must be less than or equal to regionIndexCount.` So that mitigates the issue. In #342 I've proposed an additional recommendation relevant for compilers as a further mitigation.

**Comment by PeterConstable** [comment]
Fixed by #342

**Comment by behdad** [comment]
> We already had wording, `the number of deltas that use the long ("word") representation... must be less than or equal to regionIndexCount.`

That was all considered when this was designed:

  https://github.com/googlefonts/colr-gradients-spec/issues/29#issuecomment-679415436

You were part of that discussion. You just didn't remember, so bunch of our times had to be wasted to stop you from jumping to pen...
