### ISSUE TITLE
Make DeltaSetIndexMap consistent x-spec

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#345]
After discussion w/@behdad I would like to reraise discussion of the notion that DeltaSetIndexMap should work the same regardless of context. That is, we should remove the rule that [HV]VAR are limited to format 0. Intent is twofold:

1. Implementation simplicity, you process DeltaSetIndexMap the same everywhere you see it, no special rules about how some formats are only valid in some context.
1. Future friendly. A small but distinct step toward the longer term goal of support for > 16 bit gids. No need to go back and rip out the rule about format 0 only later.

**Comment by PeterConstable** [comment]
Existing HVAR parsers would fail on a format 1 DSIM. A parser wouldn't simply ignore unless it was validating that reserved bits in the presumed-16-bit entryFormat field were zero. And if it doesn't do that, then it will be one word off when parsing the mapData data. At best, that would be garbage; at worst, who knows.

So, until there are >16-bit GIDs, wouldn't it be a good idea to recommend that compilers not generate a format 1 DSIM for HVAR / VVAR?

**Comment by PeterConstable** [comment]
>Implementation simplicity, you process DeltaSetIndexMap the same everywhere you see it, no special rules about how some formats are only valid in some context.

This is directed at font compilers, not runtime implementations. There's no problem if the runtime implementation is able to handle a format 1 DSIM in HVAR or VVAR but those are never encountered in the wild. But at this time we shouldn't have font compilers generating HVAR or VVAR with a format 1 DSIM since a lot of implementations in the wild wouldn't support that.

>Future friendly. A small but distinct step toward the longer term goal of support for > 16 bit gids. No need to go back and rip out the rule about format 0 only later.

There will be so many changes needed when that time comes, changing this at that time will not be significant overhead.

**Comment by behdad** [comment]
> > Future friendly. A small but distinct step toward the longer term goal of support for > 16 bit gids. No need to go back and rip out the rule about format 0 only later.
> 
> There will be so many changes needed when that time comes, changing this at that time will not be significant overhead.

This is bizarre argument: there's a lot of work that needs to be done then, so let's add some more to it.
