### ISSUE TITLE
Clipbox was built futureproof, make it future friendly

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#346]
@behdad pointed out I cleverly designed the clip box data structures to make it hard to support 32 bit gids in future. Make sure there is an expansion path, such as a format on either the overall list (which would become a table) or on each clip.

**Comment by PeterConstable** [comment]
Sounds good.

**Comment by PeterConstable** [comment]
The clipRecord could use uint24s or uint32s, but until needed it's more padding in a repeated record. A flag or something could be added to the ClipList that indicated the size of the GID fields in the records, maintaining compactness when larger records aren't needed. It would be good to come up with an approach to GID future proofing that was adopted in any new structs where it might be needed and would fit.

**Comment by behdad** [comment]
My current thinking is to make ClipList start with a `uint8 format`; Format 1 will use 16bit gids; Format 2 (which we can add later) will use 24bit gids. Keep all rest the same.
