### ISSUE TITLE
Improve note on bounding box

### ISSUE THREAD

**Issue by behdad** [googlefonts/colr-gradients-spec#38]
> To simplify implementation allocation of a drawing surface the bounding box of the glyph corresponding to the BaseGlyphV1Record should be taken to describe the drawing area for the COLR v1 glyph.

Somehow incorporate that the "non-color / outside-of-this-table bounding box of the glyph..." is used.

>Note: A glyf entry with two points at the diagonal extrema would suffice.

Unlike Apple's `sbix`, with this format, the non-color glyph is NOT an empty. It conveys the same concept of the glyph in simple bicolor outline.

So the note should specify that if the color drawing's bounds are beyond the non-color, then adding "a degenerate outline with two points placed at two diagonal corners of the desired bounding box would suffice".

Some systems might filter out outlines with just one point on them. That's why is better to have both points be part of the same outline than each on its own.

**Comment by PeterConstable** [comment]
A few things aren't clear to me.

>>To simplify implementation allocation of a drawing surface the bounding box of the glyph corresponding to the BaseGlyphV1Record should be taken to describe the drawing area for the COLR v1 glyph.

This sounds like a runtime implementation detail. Is that what you intend?

>Somehow incorporate that the "non-color / outside-of-this-table bounding box of the glyph..." is used.
>
>>Note: A glyf entry with two points at the diagonal extrema would suffice.
>
>Unlike Apple's sbix, with this format, the non-color glyph is NOT an empty. It conveys the same concept of the glyph in simple bicolor outline.
>
>So the note should specify that if the color drawing's bounds are beyond the non-color, then adding "a degenerate outline with two points placed at two diagonal corners of the desired bounding box would suffice".

Is this meant to be a requirement on _fonts_? A runtime implementation requirement?

**Comment by rsheeter** [comment]
I have always understood the font format to be deliberately designed to facilitate implementation wherever possible.

> Is this meant to be a requirement on fonts? A runtime implementation requirement?

The font is meant to provide the bbox (which it does already for `glyf` via header x/y min/max) by way of the bbox for the non-COLR glyph that corresponds to the BaseGlyphV1Record.

Aside: this happens already in real implementations. I was deeply confused while working on our color font compiler when I discovered some of my glyphs clipped until I put in an outline that defined the extents.

**Comment by rsheeter** [comment]
Mk1 clarification posted. @PeterConstable I tried to clarify the relationship and moved the implementation detail to a note.

**Comment by behdad** [comment]
> Aside: this happens already in real implementations. I was deeply confused while working on our color font compiler when I discovered some of my glyphs clipped until I put in an outline that defined the extents.

When the OT+SVG was being developed it was decided that the bounding box shall be calculated by the implementation. I discussed how *that* went in my (I know, 3hrs!! video):

  https://twitter.com/behdadesfahbod/status/1308924568325758978

**Comment by behdad** [comment]
Proposed changes by @rsheeter LGTM.
