### ISSUE TITLE
Why format 6?

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#40]
In the current proposal, format 6 can be used to reference a glyf outline and map it to a Paint table:

>// Paint a non-COLR glyph, filled as indicated by paint.  
struct PaintGlyph  
{  
  uint8               format; // = 6  
  uint16              gid;    // shall not be a COLR gid  
  Offset16<Paint>     paint;  
}

What does this enable that can't otherwise be implemented by creating a BaseGlyphV1 record using a virtual glyph ID, then having an associated LayerV1List with a single Paint? Is format 6 just a short hand that saves a glyph ID and a few bytes?

**Comment by PeterConstable** [comment]
After studying the new design further, IIUC a format 6 table is _the_ means by which a solid color or gradient fill is applied to a geometry. Correct?

(If so, perhaps the ordering of formats might make more sense if format 6 were instead format 0?)

**Comment by behdad** [comment]
Yes. This is *the* primary way to color glyphs.

**Comment by rsheeter** [comment]
To put it another way, if you limited yourself to only PaintGlyph using PaintSolid you'd basically have COLR v0 built with COLR v1 :) https://github.com/googlefonts/colr-gradients-spec/blob/master/colr-gradients-spec.md#high-level-design notes as much.

To me Paint Solid/Linear/Radial are fundamental and everything else builds on those so I rather like having them first. 

@PeterConstable do you think shuffling makes things materially more readable? - if so I'm ok with updating (perhaps to Solid, Linear, Radial, Glyph, Color Glyph, Transform, Composite?). If it doesn't make much difference I'd rather just make no change and close this issue.

**Comment by PeterConstable** [comment]
I think it would make sense if Glyph were right after Solid/Linear/Radial since those three fills (IIUC) are only used with Glyph; then Glyph can be used in Composite or Transform (or directly in LayerV1List). People later may think the order is strange and wonder why it was done that way. But it works as is.
