### ISSUE TITLE
PaintFormat4 transform: record or table offset?

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#42]
In `PaintTransformed`, the transform is currently shown as an inline record, in contrast to format `PaintRadialGradient` in which the transform is a table at an offset. 

I just want to confirm that's the intended design.

**Comment by behdad** [comment]
Maybe you should talk without "format 4" and "format 3" if you really want to "confirm" things.

**Comment by anthrotype** [comment]
for the PaintTransform, the transform is required (that's the whole point of it), whereas for PaintRadialGradient the transform is optional (can be null).

**Comment by rsheeter** [comment]
Confirmed to be intentional, including the fact that `PaintRadialGradient::transform` is optional. That does mean that we can't reuse 2x3's but I think that's ok; the big win is reuse of entire shapes or stacks of shapes (via `PaintColrGlyph`).

I'm going to edit OP because I changed the format #s.
