### ISSUE TITLE
Should a maximum depth for the DAG be specified?

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#43]
Is there some limit to avoid circular definitions? Or does the layout engine just check to see if a Paint at a given offset occurs more than once between any root/leaf path?

The proposal has this:

> Implementations should track the COLR gids they have seen in processing and fail if a gid is reached repeatedly.

But formats 4 and 5 reference paint tables without using a gid.

**Comment by PeterConstable** [comment]
Or is potential for circularity with formats 4 and 5 avoided because the subtable offsets are always +ve? (So you could only get back to the same format 4 or 5 subtable via a gid from format 7?)

**Comment by behdad** [comment]
Subtable offsets are always positive. So recursion only happens through gid entries in this table (and through lookup indices in GSUB/GPOS). I'm against any maximum depths requirements other than requiring *minimum*s. Suggesting 32 minimum.

**Comment by rsheeter** [comment]
Cycles are verboten so I believe *infinite* is unachievable. A production grade implementation might still cap depth but I think it's best to leave that to the implementation.

**Comment by PeterConstable** [comment]
I'm not asking to add a max. I saw cycling via the COLR glyph GID was possible and but that nothing was mentioned about Paints referenced in Transform or Composite. But then I realized they were a non issue because offsets are +ve.

A recommended minimum could be mentioned. Since LayerV1List count is uint8, would implementations be likely to assume 256 as a minimum (hence probably no need to mention)?

**Comment by rsheeter** [comment]
It's not even completely clear to me that depth is the right concept. A limit on total # of graph edges could also make sense. I'm increasingly inclined to not want to specify this. The public reference implementation and test fonts might be a better way to nudge implementations along.

**Comment by rsheeter** [comment]
Tentatively closing but please reopen if you feel strongly spec content is called for

**Comment by behdad** [comment]
Offsets in OpenType are all positive. So automatically acyclic.
