### ISSUE TITLE
default composition mode

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#44]
If a font as a format 5 paint with an invalid / unrecognized compositeMode value, what should the rendering engine do? 

<https://www.w3.org/TR/compositing-1/> defines a "normal" mode in which the source is overlaid on the destination with full opacity (B(Cb, Cs) = Cs). The CompositeMode enum doesn't include normal (and normally it wouldn't be needed).

In the unrecognized mode case, should the "normal" mode behaviour be used? Or multiply? Other?

**Comment by behdad** [comment]
@PeterConstable Can you please stop using numbers eg "format 5" and use human-understandable terms like `PaintComposite` please?

A compositing-mode that is NOT "understood" should result in no rendering for the resulting Paint.

**Comment by rsheeter** [comment]
+1 to the friendly names. @behdad do you mean effectively that Clear should be used for an unrecognized mode?

**Comment by behdad** [comment]
> @behdad do you mean effectively that Clear should be used for an unrecognized mode?

Yes I believe that's what I'm suggesting.

**Comment by PeterConstable** [comment]
The composite paint has a source and backdrop (destination). Are you suggesting that *neither* gets used?

**Comment by rsheeter** [comment]
Yes. You just give up. You have no way to know what the desired result is. Bear in mind that no reasonable COLR v1 compiler would output composite unless it wanted an "interesting" one.

**Comment by PeterConstable** [comment]
But a runtime will have to do _something_ if it encounters a bad value. Or, if the composite modes are extended in the future and an older implementation doesn't recognize the newer value.

**Comment by rsheeter** [comment]
I specified what to do in #47 as `CompositeMode       mode;   // If mode is unrecognized use 0 (Clear)`; that's what I meant by give up: you essentially stop progressing along this path through the graph.
