### ISSUE TITLE
Transform in linear/radial gradient redundant?

### ISSUE THREAD

**Issue by behdad** [googlefonts/colr-gradients-spec#45]
Originally we added an `Affine2x2` to linear and radial gradients because necessary. But since we have added an `Affine2x3` now, I believe the `Affine2x2`s can be removed.

**Comment by rsheeter** [comment]
Unless #41 is correct that we should actually have per-circle transforms on radial I agree.

@drott @anthrotype  any concern with removal of 2x2, compiler should just do PaintTransformed>PaintRadial?

**Comment by rsheeter** [comment]
Per IM the limit to 2x2 was because APIs didn't support per-circle transform. I think that means removing the 2x2 is correct, will send a PR to do so.

**Comment by rsheeter** [comment]
I think I confused myself :) Do you mean:

1. Change the `Offset32<Affine2x2> transform;` to `Offset32<Affine2x3> transform;` on `PaintRadialGradient`
   - I see we have [special rules](https://github.com/googlefonts/colr-gradients-spec/blob/master/colr-gradients-spec.md#radial-gradients) about how this applies, in particular it does *not* transform the coordinate centers
1. Delete the `transform` field from `PaintRadialGradient` and also delete all the rules about it not changing center coordinates
   - DAG can setup `PaintTransformed>PaintRadialGradient` and thereby make the circles ellipses (or shear them or rotate them or w/e). This *would* alter the circle centers as the rules that say otherwise would go away.

**Comment by PeterConstable** [comment]
I don't think transform should be deleted from PaintRadialGradient: it seems much cleaner to keep that transform there.

Currently, PaintGlyph (format 6) takes a Solid, LinearGradient or RadialGradient. And Transform (format 4) and Composite (5) take any of Transform, Composite, Glyph or ColrGlyph.

If the transform field is removed from the gradient, then PaintGlyph needs to take Solid, LinearGradient, RadialGradient or Transform, but the latter only if the Transform takes a RadialGradient. And then Transform can take Transform, Composite, Glyph, ColorGlyph, or RadialGradient, but only RadialGradient if the Transform parent is Glyph.

**Comment by behdad** [comment]
> Delete the `transform` field from `PaintRadialGradient` and also delete all the rules about it not changing center coordinates

Correct.

**Comment by anthrotype** [comment]
but then also PaintLinearGradient could be transformed (like in SVG `gradientTransform` can apply to either linear or radial gradients). Right now we have that PaintLinearGradient's optional P2 which describes the orientation of the gradient's "front" line, which was added to avoid having to add a transform to all PaintLinearGradients. Following the same line of reasoning, we can do away with that as well.

**Comment by behdad** [comment]
> which was added to avoid having to add a transform to all PaintLinearGradients

Back then we didn't have transform operation. So we added Affine2x2 to linear & radial gradients to enable what otherwise would have been impossible.

**Comment by anthrotype** [comment]
we added Affine2x2 only to radial gradients. For linear we used a third point to allow to "skew" the gradient.

**Comment by behdad** [comment]
> we added Affine2x2 only to radial gradients. For linear we used a third point to allow to "skew" the gradient.

I see. Thanks. Yes, that point, and the complex part of the spec justifying why it's needed, can be removed now. :)

**Comment by rsheeter** [comment]
Very happy with the removal of the 2x2 and all the spec language about it, will draft a PR this evening.

> Currently, PaintGlyph (format 6) takes a Solid, LinearGradient or RadialGradient. And Transform (format 4) and Composite (5) take any of Transform, Composite, Glyph or ColrGlyph.

This isn't right; for example there's nothing wrong with a PaintGlyph referring to a PaintTransformed that refers to a PaintRadialGradient.

**Comment by PeterConstable** [comment]
But what about PaintGlyph > PaintTransformed > PaintComposite.src > PaintColrGlyph > ...?

**Comment by rsheeter** [comment]
> But what about PaintGlyph > PaintTransformed > PaintComposite.src > PaintColrGlyph > ...?

I would like to lean toward being permissive, but we do need to address how things combine. That probably justifies an issue of it's own, will file on your behalf :)

**Comment by drott** [comment]
Agree with removing transforms from `PaintLinear` and `PaintRadial`. In my opinion, this even makes the algorithm a little cleaner, as there's no special code needed for handling the local matrices (radial case) or `P2` (linear case). Transformations on the gradients can be taken care of by the matrix that's currently set to the graphics context by the parent `PaintTransform`.

**Comment by rsheeter** [comment]
Per discussion, we need to think more about P2. I'm going to close the current PR pending a new idea.

**Comment by rsheeter** [comment]
How things combine has it's own issue, the transforms are gone, I think we're done here. As always please reopen if you disagree.
