### ISSUE TITLE
Circle center to circle center for radial needs illustration

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#5]
"Color stop position 1 maps to the end point of a linear gradient or the **center** of the second circle of a radial gradient."

This is non-intuitive. (More intuitive would be going from the center of one circle to _a point on the circumference of_ a second circle.) The figure for linear gradients showing P2 being different from P1 is informative and helps make clear what was non-obvious: why a linear gradient would be defined using two vectors. It would be helpful to have a figure for radial gradients that similarly illustrates the non-obvious aspect of how the second circle is used in defining a radial gradient.

**Comment by PeterConstable** [comment]
[This Direct2D doc'n](https://docs.microsoft.com/en-us/windows/win32/api/d2d1/ns-d2d1-d2d1_radial_gradient_brush_properties) has illustrations that show how the two centers interact.

**Comment by behdad** [comment]
You are right.  The intention is what you point at.  Is just the wording:

> "Color stop position 1 maps to the end point of a linear gradient or the **center** of the second circle of a radial gradient."

Should be "circumference" instead of "center" in both instances.

**Comment by PeterConstable** [comment]
This is a non-issue based on misunderstanding of the intended semantics. Closing.
