### ISSUE TITLE
Clarify how things combine

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#54]
@PeterConstable [noted](https://github.com/googlefonts/colr-gradients-spec/issues/45#issuecomment-700290187) on #45:

> But what about PaintGlyph > PaintTransformed > PaintComposite.src > PaintColrGlyph > ...?

I would like us to bias toward being permissive. I think the underlying issue is we need to add a bit more discussion around how things combine. My hope is we can define some simple guidelines.

**Comment by drott** [comment]
@PeterConstable was your question with regards to which layers are bounded or unbounded? Or what the behaviour should be for the chain you're describing? Where do you see a problem with this chain?

**Comment by PeterConstable** [comment]
What the behaviours should be. 

In the draft for OT/OFF posted [in the mpeg/off repo](https://github.com/MPEGGroup/OpenFontFormat/issues/20), the description of paint formats that take an offset to another paint state which formats that can be referenced. That was based on what, at first glance, does or doesn't make sense. If the spec is to be completely permissive on what font data can include, then it needs to be more prescriptive about what the intended behaviours should be in cases in which it's not self evident.

**Comment by drott** [comment]
I think restrictions such as: " must be one of formats 4, 5, 6, 7 " in line 226 of [colr_190_draft.pdf](https://github.com/MPEGGroup/OpenFontFormat/files/5294023/colr_190_draft.pdf) is not a restriction we want to make up -front.

`PaintComposite` can refer to a PaintFormat 1-3 as well. In this case, the blend mode needs to be taken into account to determine whether the outcome of the `PaintComposite` is an unbounded or bounded element of the graph. 

The main restriction we want to make at this point is whether the top level layer is bounded or unbounded, as described in 
https://github.com/googlefonts/colr-gradients-spec/blob/master/colr-gradients-spec.md#bounded-layers-only

In the algorithm sketch, this means that we keep flags for boundedness of each layer and collapse those upwards to the top layer, according to the table in the bounded-layers-only section.

`PaintComposite` combining a bounded with an unbounded format 1-3 Paint is for example useful when shading a glyph without explicitly restricting the gradient or solid color that we shade with.

> 1) PaintFilledGlyph > 2) PaintTransformed > 3) PaintComposite.src > 4) PaintColrGlyph > ...

Following the algorithm sketch, this means:
```
1) SaveLayer, Clip the graphics context to PaintFilledGlyph
   2) Create a new layer, apply transform to the new layer
      3) a) Paint backdrop b) create new layer c) paint src d) merge src with backdrop using mode
   2) restore graphics context state, 
1) Restore graphics context state
```

**Comment by behdad** [comment]
> In the draft for OT/OFF posted [in the mpeg/off repo](https://github.com/MPEGGroup/OpenFontFormat/issues/20), the description of paint formats that take an offset to another paint state which formats that can be referenced. That was based on what, at first glance, does or doesn't make sense.

Can I please ask @rsheeter / @davelab6 if that's what Google has contracted Peter to do: to reinterpret what the rest of us have meticulously put together into an inferior interpretation by himself? Because I have no Fucking interest in doing any work that goes through Peter's slashing.

**Comment by behdad** [comment]
Back to where I was three months ago: I don't trust Peter's fairness, objectivity, nor technical acumen, and as such refuse working on any spec work that goes through Peter's pen.

Record this as another failed experience.

**Comment by behdad** [comment]
Because I, and others, shouldn't keep looking were to fix Peter's fucking mistakes introduced on OUR precise work.

**Comment by PeterConstable** [comment]
I'm trying to get a correct understanding of the design, not slash or change it. If you guys had included me in your private discussion to change the design, I would have had a better understanding from the outset.

**Comment by rsheeter** [comment]
General: I think we might benefit from assumption of good faith on the part of others.

Regarding the the current proposal, if the spec isn't clear or we think we need more restrictions let's file an issue here rather than adding them to the draft only.

If the current draft contains things we aren't happy with then we can fix it. The proposal authors (self included) can take ownership for having written source material that was unclear. Fixing that is a good thing.

@PeterConstable is the reason there is a separate PDF to make the proposal "look like" the OFF more? If we amend the proposal to be more OFF-like could we avoid having a third (proposal, actual off, pdf derived from proposal) document?

**Comment by drott** [comment]
Behdad, I don't think the language you're using above is an acceptable form of debate. Please refrain from calling someone's work a slashing or personally attacking contributors. 

I appreciate the fixes as listed in ["Update, October 1, 2020"](https://github.com/MPEGGroup/OpenFontFormat/issues/20) which brings the documents closer together. But I second Rod's question. and we do need to bring this repo closer together with the drafts proposed in https://github.com/MPEGGroup/OpenFontFormat/issues/20 - I think there are still parts of this repo that have not been fully reflected in the `colr_190_draft_201001a.pdf`. I note that line 66 refers to a <forthcoming> section, which I assume is intended to fill those parts in.

If there is a need for clarification or if there are proposals to edit the structure of the document, for example with regards to the syntax on how we express the data structures, I suggest we do that here instead of a second transformed document, then aim for no editorial / significant changes other than input format if needed, when transferring the spec draft from here into a proposal to be merged with OFF specs.

**Comment by behdad** [comment]
I'm doing this work on my personal time out of my passion, without being paid. I have a dozen other things fighting for my time. I cannot waste time...

**Comment by behdad** [comment]
> If you guys had included me in your private discussion to change the design, I would have had a better understanding from the outset.

Oh seriously! How does the Microsoft medicine taste to you now?

You were NOT participating on the design discussions on github, so there was no reason to include you in the video meeting.

**Comment by behdad** [comment]
An editor is NOT allowed to change technical content. I REFUSE to work with Peter any longer. Gave him too many chances.

**Comment by rsheeter** [comment]
@drott made quite a few changes to the Graphical Primitives section, including addition of a note about clipping. IMHO the goals of OP have been met. Plz reopen in the event of disagreement.
