### ISSUE TITLE
Use (new) Offset24

### ISSUE THREAD

**Issue by behdad** [googlefonts/colr-gradients-spec#58]
I'm of two views in general, both of which have not been followed in the spec consistently before:

- Use types that are wide-enough that won't run out of space, even for (reasonable but) unanticipated uses (eg. 60k axes!). Avoiding `Offset16` in most cases is part of this design philosophy.

- Don't waste bytes if not necessary. Before we've been using a lot of uint16 version numbers, even separate uint16 major/minor ones. That's a waste. Currently proposal use of `uint8_t` for `format` / `Extend` / `CompositeMode` is in line with that.

Now. The very issue of alignment that Peter seems to be obsessed with in other parts of the spec, is fully ignored here.

We should introduce an `Offset24` type, and use it next to `uint8_t` types when possible, to save a byte without limiting what's reachable, and making it faster as well because fetching one (aligned) int is faster in modern memory systems than fetching one unaligned int, which is implemented as two aligned int fetches.

**Comment by behdad** [comment]
Needs one-row addition to https://docs.microsoft.com/en-us/typography/opentype/spec/otff

**Comment by PeterConstable** [comment]
> The very issue of alignment ... is fully ignored here.
...
> fetching one (aligned) int is faster in modern memory systems than fetching one unaligned int, which is implemented as two aligned int fetches.

!!!

**Comment by rsheeter** [comment]
@PeterConstable are you expressing concern with Offset24? - I was quite happy with how it fit together with our single-byte fields.

**Comment by PeterConstable** [comment]
No strong concern with Offset24. Just surprised by the self contradiction: the second statement isn't ignoring alignment.
