### ISSUE TITLE
Add mesh gradient support

### ISSUE THREAD

**Issue by atanassov** [googlefonts/colr-gradients-spec#6]
The current proposal is missing support for mesh gradients. Should this be added?

**Comment by behdad** [comment]
Another consideration was that we wanted to keep the proposal as subset of what SVG Native is considering.  @litherum is mesh gradients on the map there?

**Comment by behdad** [comment]
After reviewing this some more, I'm inclined to go without them.

**Comment by PeterConstable** [comment]
Agree on cutting mesh for COLRv1.

@atanassov I think this can be closed.

**Comment by rsheeter** [comment]
Closing; please re-open if you believe we should have mesh.

I will note that I hope that the font spec can begin to iterate somewhat faster so if we discover we need mesh we can add it in a timely fashion.

**Comment by davelab6** [comment]
Reopening and filing under the "COLRv2" milestone
