### ISSUE TITLE
Examples should show extended/shortened intervals, P2=P0

### ISSUE THREAD

**Issue by drott** [googlefonts/colr-gradients-spec#68]
@behdad says in #57 "One thing not shown is color-lines where defined internal is NOT (0,1). Showing both intervals that are a subrange of that, as well as broader (eg. (-3,.5)) etc would be great as well."

&

@rsheeter  suggested to show the simple case of P2=P0. I'll track that as an issue to update the examples further.

**Comment by PeterConstable** [comment]
@drott Is there any outstanding issue here we need to address?

**Comment by drott** [comment]
Not for the P2=P0 case. But I guess we still don't have examples for color line definitions that define stops outside [0,1]? Figures 5.9 – 5.11 talk only about the "defined" interval. We could potentially add one example for what happens when you define color stops from 0,5 to 2 or something like that.

**Comment by PeterConstable** [comment]
Current wording in 5.7.11.1.2.1 includes this (bold added here):

>Repeat: The color line is repeated over repeated multiples of the defined interval. **For example, if color stops are specified for defined interval of [0, 0.7], then the pattern is repeated above the defined interval for intervals [0.7, 1.4], [1.4, 2.1], etc.; and also repeated below the defined interval for intervals [-0.7, 0], [-1.4, -0.7], etc.** In each repeated interval, the first color is that of the farthest defined color stop. By analogy, given a sequence “ABC”, it is extended to “…ABC ABC ABC…”.

**Comment by PeterConstable** [comment]
Btw, the color line interval is #77.

**Comment by PeterConstable** [comment]
5.7.11.1.2.1 has examples of a color defined on an interval not [0, 1], so think this is covered. Closing.
