### ISSUE TITLE
a radial gradient definition could be degenerate

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#7]
I think normally the center of one circle (the gradient origin, stop position 0) would be **within** the circumference of the other circle (stop position 1). But the possibility exists that it is not: you could have two overlapping or even non-overlapping circles. 

So, what should be expected if that were the case? Do we need to treat that as invalid in OT, or just let different graphics libraries handle that however they will? (That could mean a font displays differently on different platforms.)

**Comment by behdad** [comment]
I'm not sure what you are talking about.  There are two example pictures of radial gradients in the spec and  they show the range of possibilities.  Both are supported.

**Comment by PeterConstable** [comment]
Well, I don't get the second example: it appears like a radial effect that propagates linearly. I guess it's like the conical gradient I see described [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/effects/shaders/circular-gradients). That's a bit different from a radial gradient.

Try this:
```html
<!DOCTYPE html>
<html>
<body>

<canvas id="myCanvas" width="200" height="100" style="border:1px solid #d3d3d3;">
A "degenerate" radial gradient.</canvas>

<script>
var c = document.getElementById("myCanvas");
var ctx = c.getContext("2d");

// Create gradient
var grd = ctx.createRadialGradient(25,50,5,90,60,50);
grd.addColorStop(0,"red");
grd.addColorStop(1,"white");

// Fill with gradient
ctx.fillStyle = grd;
ctx.fillRect(10,10,150,80);
</script>

</body>
</html>
```

The first circle is entirely outside the second circle. There is a visual result, and it appears the same in Chrome, Chromium Edge and Firefox; so maybe the spec'd algorithm makes unambiguous the required result in this situation. But it's not what I would have called a "radial" gradient, and the fact that the spec even allows a case like this to be created makes it counter-intuitive.

The intent of `createRadialGradient` appears to be like that for how radial gradients are defined in [Direct2D](https://docs.microsoft.com/en-us/windows/win32/direct2d/direct2d-brushes-overview): so that the origin of the color gradation can be different from the origin of the circle that defines the extent. Certainly the visual examples I could find for `createRadialGradient` demonstrated it being used like that: the first circle is entirely within the second. (E.g., [on MDN](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createRadialGradient), [W3Schools](https://www.w3schools.com/html/html5_canvas.asp).) Direct2D provides the capability without allowing for the "degenerate" cases. 

But maybe someone thinks what I'm calling "degenerate" is useful. (I mean "degenerate" in the sense that the result is not what anybody would otherwise think of as a radial gradient.)

[Skia](https://skia-doc.commondatastorage.googleapis.com/doxygen/doxygen/html/classSkGradientShader.html) doesn't define radial gradients with two circles, but it does support _conical_ gradients with two circles (see the earlier link for an example. I guess the effect shown in the Direct2D doc'n might be achievable using a conical gradient in which the first circle is entirely contained within the second. But in the case that they are not, the result appears to different from what I see in Edge and Firefox for `createRadialGradient`.

**Comment by PeterConstable** [comment]
This spec for radial gradient appears to have its roots in the PDF specification for a _Type 3 shading_. (See p. 310f in [PDF Reference v1.7](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdf_reference_archive/pdf_reference_1-7.pdf).)

>Note the following points:
>
> * If one of the starting and ending circles entirely contains the other, the shading depicts a sphere...
> * If neither circle contains the other, the shading depicts a cone. If the starting circle is larger, the cone appears to point out of the page. If the ending circle is larger, the cone appears to point into the page...

It takes the same 6 coordinate/distance inputs: `[x0, y0, r0, x1, y1, r1]`. But the results described are not what I see in Chrome, Edge or Firefox for `createRadialGradient`.

If we define PaintFormat3 with c0, r0, c1, r1, it might be better to refer to it as a "conical gradient". But I think there should be visual examples that show what the expected result is in different situations.

**Comment by PeterConstable** [comment]
On reading the PDF spec further, maybe the result I see in Chrome, etc. for `createRadialGradient` is consistent with PDF:

>The color blend is based on a family of _blend circles_ interpolated **between the starting and ending circles**...

In the result I saw in Chrome, etc, the interior of the ending circle is white (the end colour), I guess because the gradient ends at the circle boundary. Here how it's described in the HTML spec:

>This effectively creates a cone, touched by the two circles defined in the creation of the gradient, with the part of the cone before the start circle (0.0) using the color of the first offset, the part of the cone after the end circle (1.0) using the color of the last offset, and areas outside the cone untouched by the gradient (transparent black).

(Btw, this doesn't seem to me to be the behaviour shown in the second example of your doc, which has a gradient fill inside the starting circle. IIUC, that result would have to involve two gradients: one that has r0 = r1, and another that has r0 = 0 and r1 = the same radius as in the other gradient.)

Now, I note that the HTML spec doesn't appear to define an extend mode. Skia (at least the [SkiaSharp](https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skshadertilemode?view=skiasharp-1.68.1) API) does support one extend, for extending past the ending circle.

PDF, on the other hand, defines two extend parameters: one for before the starting circle (t<0) and one for after the ending circle (t>1). If we add one, should we reserve a field in case we want to add the other later? (It would mean extend specified in the Paint table, not in a ColorLine table. That may be better anyway: it would allow the same color line to be used in different contexts with different extend modes — similar rationale to not specifying alpha in a palette entry.)

**Comment by PeterConstable** [comment]
I've created PR #33 which would resolve this issue.

**Comment by rsheeter** [comment]
I like the way (https://whatpr.org/html/3287/canvas.html, search for "effectively creates a cone") handles this: call the construct "radial gradient" but touch on cones when describing what radial gradient is.

The current PR is more invasive, I suggest we mimic the softer touch:

1. Leave the majority of the places the text uses "radial gradient" untouched, the construct remains "radial gradient"
1. Add a note to the radial gradient section mentioning cone

**Comment by behdad** [comment]
Whatever Rod is happy with I'm happy with. I just want to emphasize again that a conical gradient is something different that our model does *not* support.

**Comment by PeterConstable** [comment]
And I'll emphasize again that names for gradient types don't follow ubiquitous conventions and are ambiguous

**Comment by rsheeter** [comment]
> names for gradient types don't follow ubiquitous conventions 

Pardon my density but I'm failing to spot this. When I searched for the text from the HTML spec it seems to be used to clarify the behavior of a "radial gradient."

> and are ambiguous

This seems like it needs to be fixed regardless of naming

Seems like there are changes to be made here so I'm surprised this is closed?

**Comment by PeterConstable** [comment]
No longer an issue: there was confusion about what meaning of "radial gradient", and that's now clarified.
