### ISSUE TITLE
Elaborate on color stop range

### ISSUE THREAD

**Issue by drott** [googlefonts/colr-gradients-spec#77]
Explain in more detail what happens when the range is defined on an interval other than 0 to 1. Smaller, larger, partially overlapping, etc.

**Comment by rsheeter** [comment]
After reading the examples on #76 with larger #s (unlike prior examples, which were very 0..1 focused) I'm again wondering why this is required: "In the interval [0, 1] the color line must contain at least one color stop, but may contain multiple color stops that define the gradient." Two concerns:

1. It reads as implying the stops are *only* in 0..1 to me.
1. While doubtless typically true why does this need to be required?

**Comment by svgeesus** [comment]
Yeah it doesn't make sense (unless color stops outside the range [0,1] are **discarded**)

For example a gradient with a stop of red at -0.1, and no other stops, is well defined (and will give a solid red fill). A gradient with three stops;

red, -2.0
yellow, 0.1
green, 1.0

will start with a slightly orangish yellow at 0.0, going on to yellow at 0.1 and a yellow-to-green for the rest of the [0,1] range.

**Comment by svgeesus** [comment]
For a color stop record, the [stopOffset]https://github.com/googlefonts/colr-gradients-spec#colorstop-record) is [VarF2Dot14 record](https://github.com/googlefonts/colr-gradients-spec#varf2dot14-record):

> Values are inherently limited to [-2., 2). In some contexts, limited to the [-1., 1.] or [0., 1.].

I'm unable to tell from that if the valid range for color stops is `[-2., 2)` or `[0., 1.]` or what.

**Comment by PeterConstable** [comment]
@drott I think we have since addressed this in current wording. Can this be closed?

**Comment by drott** [comment]
> A color line is defined with at least one color stop within the interval [0, 1]. 

is still present in "5.7.11.1.2.1 Color Lines" - which we still may want to remove, wouldn't we?

**Comment by drott** [comment]
Closing - I think what's left here is #148 .

**Comment by PeterConstable** [comment]
@drott  I'm pretty sure I had left "at least one" because I had gotten that from text you had drafted at some point. If you don't  think it's needed, I could drop that. But you closed this already, so I'm not sure what you think would be best. 

I don't see it as too critical since it's not a particular burden for font developers. The main annoyance would be that it amounts to a conformance requirement, so validators should check for at least one in range.
