### ISSUE TITLE
[bikeshed] Rename LayerV1List to PaintList?

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/colr-gradients-spec#78]
The `LayerV1List` no longer contains an array of `LayerV1Record`s. It now contains an array of `Paint`s. What used to be called a "layer" record is now subsumed as another Paint format 4 (`PaintGlyph`).
I find it a bit confusing that we subtly change terminology while we define the structs from talking about "layers" (e.g. in the name "LayerV1List") to talking about "paints" (e.g. where we say "LayerV1List" contains list of "paints").
I believe I would find it clearer if we only talked about Paints instead of layers.

I understand that multiple paints are "layered" (as if composited with previous paint using SOURCE_OVER operator) following the z-order of LayerV1List. And that a single "layer" is understood as one (bounded) DAG of paints; so the LayerV1List is a sequence of paint DAGs layered over each other.

What do you think of renaming `LayerV1List` to `PaintList`? We'd also ditch the "V1" from the name, since this new structure is quite unlike the V0 one.

Feel free to dismiss/ignore, I don't mean to open a can of worms.

**Comment by rsheeter** [comment]
In defense of LayerV1List it is still very similar to the concept of a list of layers in v0.

I'm fine with either name as long as we change it relatively soon. Assigning to you, please either send a PR to rename or close this issue :)

**Comment by anthrotype** [comment]
Nah. I think it's fine like this.
