### ISSUE TITLE
How aligned with OFF do we want the proposal to be?

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#80]
In #74 there was some discussion of where the Constraints section should live: under COLR table or at a higher level. Currently it is at OFF Changes > COLR table > Constraints, which is roughly where it appears it would land in OFF.

I think if we think about how closely we want to align with OFF the answer to where Constraints and some of the content in Introduction (Back compat, Graphical primitives) should land will become more clear. The advantage of trying to align very closely with OFF is it minimizes the need for an editor to restructure the content. The disadvantage is it may put the content into a layout we wouldn't otherwise choose.

I'm happy to move things around based on what we decide.

@drott wdyt?

**Comment by davelab6** [comment]
Can this be closed?

**Comment by rsheeter** [comment]
Given that #83 moves us even further into alignment with OFF I think it can. As always reopen if dissatisfied :)
