### ISSUE TITLE
Updates per WG3 breakout group

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#83]
High level: it wasn't quite clear how the introductory content folds into OFF. Make that clearer. I *think* that means much of it needs to be landed in the COLR table.

The color table currently exists in `5.7 Optional tables`. I think we should propose it moving up (5.x COLR) similar to how SVG is 5.5.

I believe the suggested order of content for COLR was:

- intro section describing primitives
- table structures / formats
- examples 

We *might* want to emphasize the variable capabilities more.

**Comment by drott** [comment]
I think that's accurate. The way I understood it was: have an introductory section as part of the COLR table section, then in each table section add some more detail and cross/back-references to introductory section for each table struct where it make sense.

**Comment by svgeesus** [comment]
> The color table currently exists in 5.7 Optional tables. I think we should propose it moving up (5.x COLR) similar to how SVG is 5.5.

Yes, I always found it odd how some things were in Optional tables, but not all the optional ones. The grouping at [The OpenType Font File](https://docs.microsoft.com/en-us/typography/opentype/spec/otff#font-tables), with a section Tables Related to Color Fonts makes more sense to me.

Also, if there is too much introductory material, it would be better to put that into some other document (and expand it with a lot more examples and renderings than would be usual for an ISO specification). But make sure the introductory material doesn't hide any requirements ("shall", etc).

**Comment by svgeesus** [comment]
> We might want to emphasize the variable capabilities more.

Yes, with some examples, and also listing COLR in [Tables used for OpenType Font Variations](https://docs.microsoft.com/en-us/typography/opentype/spec/otff#tables-used-for-opentype-font-variations)

**Comment by PeterConstable** [comment]
Aside from variation examples (which aren't essential for 5.7.11 COLR), additions for Amendment 2 have been added. (Re-organization of OFF clauses at levels 1 or 2 wouldn't be appropriate in Amd 2.)
