### ISSUE TITLE
Conic gradients

### ISSUE THREAD

**Issue by davelab6** [googlefonts/colr-gradients-spec#84]
https://twitter.com/LeaVerou/status/1315655737608146945?s=19

Possible v2 feature?

**Comment by rsheeter** [comment]
Very cool. +1 to v2 unless anyone emerges claiming they simply MUST have it to make use of v1.

**Comment by behdad** [comment]
Honestly I'd put them in since software needs to be updated...

**Comment by svgeesus** [comment]
I would certainly encourage adding Conic gradients to V2. The gradient line is simply a circle. [CanIUse conic gradient](https://caniuse.com/css-conic-gradients)

**Comment by PeterConstable** [comment]
In F2F discussion with Rod, Dominik, Cosimo, deciding to incorporate this now, in COLR v1.

**Comment by PeterConstable** [comment]
This has been added now for COLR v1, so closing.
