### ISSUE TITLE
Adjust PaintColrGlyph to directly express subset of layers

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/colr-gradients-spec#86]
In playing with PaintColrGlyph for Noto Emoji I realized that to reuse a subset of layers from a glyph you end up having to extract a new BaseGlyphV1Record and point all users at it. This makes reuse of a small # of layers result in an increase in filesize.

Visualization of what the layer graphs currently end up looking like @ https://codepen.io/rs42/pen/qBNRwew?editors=1000.

Thinking "aloud", what if we amend format 5 to directly express of "reuse some layers"? - sketch:

```C++
// 5 bytes. 
// In a LayerV1List each pointer costs 4 bytes
// For a single paint you just point directly, for 2+ consecutive you "win" by using format 5
PaintColrSlice
  uint8 format // 5
  uint16 glyphID
  uint8 firstLayer
  uint8 lastLayer
```

In this model the first clock face happily draws it's layers, the second comes along and wherever it has a run of at least 2 of the same layers it sticks in a format 5 entry.

As @anthrotype noted when I initially filed this on the wrong repo, this also saves consumption of a glyphid when you extract a set of layers into a new base record so they can be shared.

In local test the Noto clock faces (mostly reused shapes) compiled to a 3308 font without PaintColrGlyph, a 3248 byte font with the old PaintColrGlyph and a 2436 byte font with the propose PaintColrSlice.

**Comment by drott** [comment]
> In local test the Noto clock faces (mostly reused shapes) compiled to a 3308 font without PaintColrGlyph, a 3248 byte font with the old PaintColrGlyph and a 2436 byte font with the propose PaintColrSlice. 

Great to have the data, how do these come out after woff2?

**Comment by PeterCon** [comment]
Took a look at PR #87, and the current state seems to lack coherence (transitional?): 

* Above you describe changing format 5.
* In the PR, the initial doc'n of format 5 is changed, but in the C++ implementation it's unchanged. Instead, a new format, 8, is added.
* In the PR, C++ impl'n (but not the initial doc'n),  BaseGlyphV1Record no longer has an offset to a LayerV1List, but instead has an offset to a Paint. 

?? 
Is format 8 a replacement for LayerV1List?
