### ISSUE TITLE
OT spec should use simple structure specs that are easily translatable to different implementation languages

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#9]
The draft makes use of C++ templates and unions. These are fine for implementations but should not be used in the OpenType spec.

(Not really a problem since conceptually these are just notational short hands to save writing out multiple structure specs.)

**Comment by behdad** [comment]
> (Not really a problem since conceptually these are just notational short hands to save writing out multiple structure specs.)

Longterm we should consider if switching to something closer to the C++ or IDL or something more code-like is a good idea.  Independently, to consider whether having template-like constructs are a good idea (even if we keep presentation as tables.)

**Comment by PeterConstable** [comment]
I think the spec should describe structures in a way that is clear and easily translatable to any language by developers that might be familiar only with certain languages, and not specifically C++.

**Comment by PeterConstable** [comment]
I have a draft of descriptions for structures that follows existing conventions of the OT spec, [here](https://github.com/PeterConstable/OT_Drafts/blob/master/COLR_V1/COLRv1formats_rev4.md).

Closing.
