### ISSUE TITLE
Make PaintColrLayers format 0?

### ISSUE THREAD

**Issue by PeterCon** [googlefonts/colr-gradients-spec#90]
Given the latest design change, PaintColrLayers basically replaces the LayersV1List tables of the previous design. (The new LayersV1List is a global array; the per-base-glyph data in the previous LayersV1List tables now is held in PaintColrLayers.) That makes PaintColrLayers pretty fundamental in the structure of a color glyph description. From that perspective, it could seem odd, then, that it's the *8th* paint format, not the 1st format. Would it make sense to renumber the formats to make this format 1?

So far, we've avoided having a format 0. Is there a particular reason? If not, a less disruptive change would be to make PaintColrLayers format 0.

**Comment by drott** [comment]
Sounds good to me to renumber `PaintColrLayers` to be format 1. Shifting the numbers is no big problem from my perspective. I'll draft a PR.

**Comment by anthrotype** [comment]
I think format 0 (without renumbering the other paint formats) should also be ok

**Comment by anthrotype** [comment]
I got already quite used to seeing format-1 as solid, format-2 as linear and format-3 as radial in the ttx dumps from our WIP fonttools branch.

**Comment by drott** [comment]
> So far, we've avoided having a format 0.

@PeterCon, did you mean in this COLRv1 draft, or in other tables as well?

If that's the case, then I think for consistency it'd be good to start numbering from 1?

**Comment by anthrotype** [comment]
in fontTools otData.py, the only subtable whose name ends with "Format0" are from AAT tables, all the OpenType format-switching tables seem to start with "Format1". But besides consistency, I don't see why format 0 would create a problem. In a way, this would single out PaintColrLayers as special in that it is a "meta" paint (a paint of paints if you like), so a format 0 could make sense. But I don't really mind either way (even keeping current format8 is fine by me).
