### ISSUE TITLE
Is PaintColrGlyph redundant?

### ISSUE THREAD

**Issue by PeterCon** [googlefonts/colr-gradients-spec#91]
PaintColrGlyph allows specification of a sub-graph by referencing a base glyph ID, which is an indirect reference to a BaseGlyphV1Record, which will typically provide an indirect reference to a PaintColrLayers table. What functionality would be lost if we removed PaintColrGlyph and only had PaintColrLayers?

**Comment by drott** [comment]
The background has been that implementations may have an optimized path of bitblitting a previously rendered glyph from a glyph cache, in that case, the work of traversing the graph again would be saved and be replaced by just placing the previously rasterized glyph in place. In that sense `PaintcolrGlyph` serves as the reference for accessing such a glyph cache entry.

Okay to close with this explanation?

**Comment by PeterConstable** [comment]
Sure: close.

**Comment by PeterConstable** [comment]
#105 adds a note explaining this rationale.

**Comment by drott** [comment]
Thanks for the note, closing.
