### ISSUE TITLE
PaintComposite supporting both composition and blending

### ISSUE THREAD

**Issue by PeterConstable** [googlefonts/colr-gradients-spec#92]
I'm wondering if the current CompositeMode enum should be split into two separate enums, one for PD compositing modes and a separate enum for blending modes; and then modify the spec for PaintComposite to allow both to be specified at once.

In the current draft, PaintComposite takes a single CompositeMode value, where CompositeMode is an enum with values for Porter-Duff composition modes and also blending modes. This entails that the PD composition modes and blending modes are mutually exclusive—that is, a PaintComposite can specify either a composition mode or a blending mode, but not both.

However, <https://www.w3.org/TR/compositing-1/> describes composition modes and blending modes as complementary. 

>In the model described in this specification there are two steps to the overall compositing operation - Porter-Duff compositing and blending.
>
>The blending step determines how the colors from the graphic element and the backdrop interact.
>
>Typically, the blending step is performed first, followed by the Porter-Duff compositing step...

The composition done by the basic layering (PaintColrLayers + LayersV1List) is (I assume) simple alpha compositing. That's equivalent to using the normal blend mode with source-over PD compositing. (Note: The current draft says COMPOSITE_SRC_OVER is used, but that only identifies the composition mode.) If someone just wants to change the blend mode to something else, multiply for example, they can do that with a single PaintComposite, specifying COMPOSITE_MULTIPLY. A composition mode of source-over would be assumed. Or, if they want to change the composition mode to something else, source-atop for example, they can do that with a single PaintComposite, specifying COMPOSITE_SRC_ATOP. But if they want to change both, they'd need to chain two PaintComposites. 

(With two chained PaintComposites, I'm not sure if the ordering would matter.)

Note with the current draft there's also a gap: if a PD composite mode is specified, then some blending mode must be assumed, but that's not made clear. Similarly, if a blending mode is specified, then some PD composite mode must be assumed—presumably source-over, but again that's not made clear.

Having separate enums and ability to specify both would resolve these.

Alternately, I wonder if the PD composite modes are really needed: the effects can all be implemented without too much difficulty in other means. (E.g., destination-over simply means re-ordering layers; source-atop is achieved by having the PaintGlyph of the source within the fill subtree of the PaintGlyph of the destination.)

**Comment by PeterConstable** [comment]
I gather part of the reason for the current proposal, unifying PD composition modes and blend modes into one enum, is that is what is supported in some libraries. ([WHAT WG Canvas spec](https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-globalcompositeoperation) states that `globalCompositeOperation` can take all values defined in [Compositing and Blending](https://drafts.fxtf.org/compositing/), though it isn't clear if that's just the _compositing_ values, or also the blending values. I gather it means both.)

But if the normative reference is to <https://www.w3.org/TR/compositing-1/>, then that is pretty clear that compositing and blending are _distinct_ operations, and that the different blending modes can be combined with the different compositing modes. For instance:

>For simplicity, all the [blending] examples in this chapter use source-over compositing.

(The clear implication of that is that the different blends can be combined with other compositing modes.) So, if these are combined into a single enum, then _some_ compositing mode must be assumed when a blending mode is selected, and vice versa. That should be made clear.

**Comment by rsheeter** [comment]
As per f2f, I believe the current structure matches how {Skia, Cairo, Core Graphics, D2D} approach things: a single enum for how to combine two things. 

If we had two separate fields [blend, composite] we'd have to have a note about order of operations. We have one field and the ability to nest paints so you can model whatever order you see fit very explicitly.

The composite modes are widely supported and some (for example Source/Dest In/Out) are not trivially reproducible using layer order. As they are well documented and widely supported by spec and graphic library authors (who definitely know more about graphics than me!) I'm inclined to follow their lead and retain them all rather than to trim the list.

Closing; please reopen if you disagree.
